// File contents generated by scripts/generate.js
export const backgroundControlBrandRest = "var(--smtc-background-control-brand-rest, var(--colorBrandBackground))";
export const backgroundControlBrandHover = "var(--smtc-background-control-brand-hover, var(--colorBrandBackgroundHover))";
export const backgroundControlBrandPressed = "var(--smtc-background-control-brand-pressed, var(--colorBrandBackgroundPressed))";
export const backgroundControlNeutralRest = "var(--smtc-background-control-neutral-rest, var(--colorNeutralBackground1))";
export const backgroundControlNeutralHover = "var(--smtc-background-control-neutral-hover, var(--colorNeutralBackground1Hover))";
export const backgroundControlNeutralPressed = "var(--smtc-background-control-neutral-pressed, var(--colorNeutralBackground1Pressed))";
export const backgroundControlNeutralDisabled = "var(--smtc-background-control-neutral-disabled, var(--colorNeutralBackgroundDisabled))";
export const backgroundControlOutlineRest = "var(--smtc-background-control-outline-rest, var(--colorNeutralBackground1))";
export const backgroundControlOutlineHover = "var(--smtc-background-control-outline-hover, var(--colorNeutralBackground1Hover))";
export const backgroundControlOutlinePressed = "var(--smtc-background-control-outline-pressed, var(--colorNeutralBackground1Pressed))";
export const backgroundControlOutlineDisabled = "var(--smtc-background-control-outline-disabled, var(--colorNeutralBackgroundDisabled))";
export const backgroundControlSubtleRest = "var(--smtc-background-control-subtle-rest, var(--colorSubtleBackground))";
export const backgroundControlSubtleHover = "var(--smtc-background-control-subtle-hover, var(--colorSubtleBackgroundHover))";
export const backgroundControlSubtlePressed = "var(--smtc-background-control-subtle-pressed, var(--colorSubtleBackgroundPressed))";
export const backgroundControlSubtleDisabled = "var(--smtc-background-control-subtle-disabled, var(--colorNeutralBackgroundDisabled))";
export const foregroundControlNeutralPrimaryRest = "var(--smtc-foreground-control-neutral-primary-rest, var(--colorNeutralForeground1))";
export const foregroundControlNeutralPrimaryHover = "var(--smtc-foreground-control-neutral-primary-hover, var(--colorNeutralForeground1Hover))";
export const foregroundControlNeutralPrimaryPressed = "var(--smtc-foreground-control-neutral-primary-pressed, var(--colorNeutralForeground1Pressed))";
export const foregroundControlOnTransparentRest = "var(--ctrl-foreground-control-on-transparent-rest, var(--smtc-foreground-control-on-transparent-rest, var(--colorNeutralForeground2)))";
export const foregroundControlOnTransparentHover = "var(--ctrl-foreground-control-on-transparent-hover, var(--smtc-foreground-control-on-transparent-hover, var(--colorNeutralForeground2BrandHover)))";
export const foregroundControlOnTransparentPressed = "var(--ctrl-foreground-control-on-transparent-pressed, var(--smtc-foreground-control-on-transparent-pressed, var(--colorNeutralForeground2BrandPressed)))";
export const foregroundControlNeutralPrimaryDisabled = "var(--smtc-foreground-control-neutral-primary-disabled, var(--colorNeutralForegroundDisabled))";
export const foregroundControlOnBrandRest = "var(--smtc-foreground-control-on-brand-rest, var(--colorNeutralForegroundOnBrand))";
export const foregroundControlOnOutlineRest = "var(--smtc-foreground-control-neutral-primary-rest, var(--colorNeutralForeground1))";
export const foregroundControlOnOutlineHover = "var(--smtc-foreground-control-neutral-primary-hover, var(--colorNeutralForeground1Hover))";
export const foregroundControlOnOutlinePressed = "var(--smtc-foreground-control-neutral-primary-pressed, var(--colorNeutralForeground1Pressed))";
export const foregroundControlOnOutlineDisabled = "var(--smtc-foreground-control-neutral-primary-disabled, var(--colorNeutralForegroundDisabled))";
export const strokeControlOnNeutralRest = "var(--ctrl-stroke-control-on-neutral-rest, var(--smtc-stroke-control-on-neutral-rest, var(--colorNeutralStroke1)))";
export const strokeControlOnNeutralHover = "var(--ctrl-stroke-control-on-neutral-hover, var(--smtc-stroke-control-on-neutral-hover, var(--colorNeutralStroke1Hover)))";
export const strokeControlOnNeutralPressed = "var(--ctrl-stroke-control-on-neutral-pressed, var(--smtc-stroke-control-on-neutral-pressed, var(--colorNeutralStroke1Pressed)))";
export const strokeControlOnNeutralDisabled = "var(--ctrl-stroke-control-on-neutral-disabled, var(--smtc-stroke-control-on-neutral-disabled, var(--colorNeutralStrokeDisabled)))";
export const strokeControlOutlineRest = "var(--smtc-stroke-control-outline-rest, var(--colorNeutralStroke1))";
export const strokeControlOutlineHover = "var(--smtc-stroke-control-outline-hover, var(--colorNeutralStroke1Hover))";
export const strokeControlOutlinePressed = "var(--smtc-stroke-control-outline-pressed, var(--colorNeutralStroke1Pressed))";
export const strokeControlOutlineDisabled = "var(--smtc-stroke-control-outline-disabled, var(--colorNeutralStrokeDisabled))";
export const strokeWidthControlOutlineRest = "var(--smtc-stroke-width-default, var(--strokeWidthThin))";
export const strokeWidthControlOutlineHover = "var(--smtc-stroke-width-default, var(--strokeWidthThin))";
export const strokeWidthControlOutlinePressed = "var(--smtc-stroke-width-default, var(--strokeWidthThin))";
export const controlFocusInnerStrokeColor = "var(--smtc-control-focus-inner-stroke-color, var(--colorStrokeFocus1))";
export const controlFocusOuterStrokeColor = "var(--smtc-control-focus-outer-stroke-color, var(--colorStrokeFocus2))";
export const nullColor = "var(--smtc-null-color, var(--colorTransparentBackground))";
export const textStyleDefaultRegularFontFamily = "var(--smtc-text-style-default-regular-font-family, var(--fontFamilyBase))";
export const textRampBody2FontSize = "var(--smtc-text-ramp-body-2-font-size, var(--fontSizeBase300))";
export const textControlButtonWeight = "var(--ctrl-text-control-button-weight, var(--smtc-text-control-button-weight, var(--fontWeightSemibold)))";
export const textRampBody2LineHeight = "var(--smtc-text-ramp-body-2-line-height, var(--lineHeightBase300))";
export const paddingControlHorizontalDefault = "var(--smtc-padding-control-horizontal-default, var(--spacingHorizontalM))";
export const gapControlDefault = "var(--smtc-gap-control-default, var(--spacingHorizontalSNudge))";
export const controlFocusOuterStrokeWidth = "var(--smtc-control-focus-outer-stroke-width, var(--strokeWidthThick))";
export const controlFocusInnerStrokeWidth = "var(--smtc-control-focus-inner-stroke-width, var(--strokeWidthThin))";
export const cornerControlRest = "var(--smtc-corner-control-rest, var(--borderRadiusMedium))";
export const cornerControlHover = "var(--smtc-corner-control-hover, var(--borderRadiusMedium))";
export const cornerControlPressed = "var(--smtc-corner-control-pressed, var(--borderRadiusMedium))";
export const cornerSmallControlRest = "var(--smtc-corner-small-control-rest, var(--borderRadiusSmall))";
export const cornerSmallControlHover = "var(--smtc-corner-small-control-hover, var(--borderRadiusSmall))";
export const cornerSmallControlPressed = "var(--smtc-corner-small-control-pressed, var(--borderRadiusSmall))";
export const cornerLargeControlRest = "var(--smtc-corner-large-control-rest, var(--borderRadiusLarge))";
export const cornerLargeControlHover = "var(--smtc-corner-large-control-hover, var(--borderRadiusLarge))";
export const cornerLargeControlPressed = "var(--smtc-corner-large-control-pressed, var(--borderRadiusLarge))";
export const cornerControlCircular = "var(--smtc-corner-control-circular, var(--borderRadiusCircular))";
export const cornerControlNone = "var(--smtc-corner-control-none, var(--borderRadiusNone))";
export const gapSmallControlDefault = "var(--smtc-gap-small-control-default, var(--spacingHorizontalXS))";
export const paddingSmallControlVertical = "var(--smtc-padding-small-control-vertical, var(--spacingHorizontalS))";
export const textRampCaption1FontSize = "var(--smtc-text-ramp-caption-1-font-size, var(--fontSizeBase200))";
export const textRampCaption1LineHeight = "var(--smtc-text-ramp-caption-1-line-height, var(--lineHeightBase200))";
export const textRampCaption1FontWeight = "var(--smtc-text-ramp-caption-1-font-weight, var(--fontWeightRegular))";
export const paddingLargeControlVertical = "var(--smtc-padding-large-control-vertical, var(--spacingHorizontalL))";
export const textRampBody3FontSize = "var(--smtc-text-ramp-body-3-font-size, var(--fontSizeBase400))";
export const textRampBody3LineHeight = "var(--smtc-text-ramp-body-3-line-height, var(--lineHeightBase400))";
export const textRampBody3FontWeight = "var(--smtc-text-ramp-body-3-font-weight, var(--fontWeightRegular))";
export const curveControlStateTransition = "var(--smtc-curve-control-state-transition, var(--curveEasyEase))";
export const durationControlStateTransition = "var(--smtc-duration-control-state-transition, var(--durationFaster))";
export const strokeControlNoneRest = "var(--smtc-stroke-control-none-rest, var(--colorTransparentStroke))";
export const strokeControlNoneHover = "var(--smtc-stroke-control-none-hover, var(--colorTransparentStroke))";
export const strokeControlNonePressed = "var(--smtc-stroke-control-none-pressed, var(--colorTransparentStroke))";
export const backgroundControlNeutralSelected = "var(--smtc-background-control-neutral-selected, var(--colorNeutralBackground1Selected))";
export const strokeControlNoneSelected = "var(--smtc-stroke-control-none-selected, var(--colorTransparentStroke))";
export const foregroundControlNeutralSelected = "var(--smtc-foreground-control-neutral-selected, var(--colorNeutralForeground1Selected))";
export const backgroundControlBrandSelected = "var(--smtc-background-control-brand-selected, var(--colorBrandBackground1Selected))";
export const foregroundControlOnBrandSelected = "var(--smtc-foreground-control-on-brand-selected, var(--colorNeutralForegroundOnBrand))";
export const backgroundControlSubtleSelected = "var(--smtc-background-control-subtle-selected, var(--colorSubtleBackgroundSelected))";
export const backgroundControlOutlineSelected = "var(--smtc-background-control-outline-selected, var(--colorTransparentBackgroundSelected))";

export const tokens = {
  backgroundControlBrandRest: "var(--smtc-background-control-brand-rest, var(--colorBrandBackground))",
  backgroundControlBrandHover: "var(--smtc-background-control-brand-hover, var(--colorBrandBackgroundHover))",
  backgroundControlBrandPressed: "var(--smtc-background-control-brand-pressed, var(--colorBrandBackgroundPressed))",
  backgroundControlNeutralRest: "var(--smtc-background-control-neutral-rest, var(--colorNeutralBackground1))",
  backgroundControlNeutralHover: "var(--smtc-background-control-neutral-hover, var(--colorNeutralBackground1Hover))",
  backgroundControlNeutralPressed: "var(--smtc-background-control-neutral-pressed, var(--colorNeutralBackground1Pressed))",
  backgroundControlNeutralDisabled: "var(--smtc-background-control-neutral-disabled, var(--colorNeutralBackgroundDisabled))",
  backgroundControlOutlineRest: "var(--smtc-background-control-outline-rest, var(--colorNeutralBackground1))",
  backgroundControlOutlineHover: "var(--smtc-background-control-outline-hover, var(--colorNeutralBackground1Hover))",
  backgroundControlOutlinePressed: "var(--smtc-background-control-outline-pressed, var(--colorNeutralBackground1Pressed))",
  backgroundControlOutlineDisabled: "var(--smtc-background-control-outline-disabled, var(--colorNeutralBackgroundDisabled))",
  backgroundControlSubtleRest: "var(--smtc-background-control-subtle-rest, var(--colorSubtleBackground))",
  backgroundControlSubtleHover: "var(--smtc-background-control-subtle-hover, var(--colorSubtleBackgroundHover))",
  backgroundControlSubtlePressed: "var(--smtc-background-control-subtle-pressed, var(--colorSubtleBackgroundPressed))",
  backgroundControlSubtleDisabled: "var(--smtc-background-control-subtle-disabled, var(--colorNeutralBackgroundDisabled))",
  foregroundControlNeutralPrimaryRest: "var(--smtc-foreground-control-neutral-primary-rest, var(--colorNeutralForeground1))",
  foregroundControlNeutralPrimaryHover: "var(--smtc-foreground-control-neutral-primary-hover, var(--colorNeutralForeground1Hover))",
  foregroundControlNeutralPrimaryPressed: "var(--smtc-foreground-control-neutral-primary-pressed, var(--colorNeutralForeground1Pressed))",
  foregroundControlOnTransparentRest: "var(--ctrl-foreground-control-on-transparent-rest, var(--smtc-foreground-control-on-transparent-rest, var(--colorNeutralForeground2)))",
  foregroundControlOnTransparentHover: "var(--ctrl-foreground-control-on-transparent-hover, var(--smtc-foreground-control-on-transparent-hover, var(--colorNeutralForeground2BrandHover)))",
  foregroundControlOnTransparentPressed: "var(--ctrl-foreground-control-on-transparent-pressed, var(--smtc-foreground-control-on-transparent-pressed, var(--colorNeutralForeground2BrandPressed)))",
  foregroundControlNeutralPrimaryDisabled: "var(--smtc-foreground-control-neutral-primary-disabled, var(--colorNeutralForegroundDisabled))",
  foregroundControlOnBrandRest: "var(--smtc-foreground-control-on-brand-rest, var(--colorNeutralForegroundOnBrand))",
  foregroundControlOnOutlineRest: "var(--smtc-foreground-control-neutral-primary-rest, var(--colorNeutralForeground1))",
  foregroundControlOnOutlineHover: "var(--smtc-foreground-control-neutral-primary-hover, var(--colorNeutralForeground1Hover))",
  foregroundControlOnOutlinePressed: "var(--smtc-foreground-control-neutral-primary-pressed, var(--colorNeutralForeground1Pressed))",
  foregroundControlOnOutlineDisabled: "var(--smtc-foreground-control-neutral-primary-disabled, var(--colorNeutralForegroundDisabled))",
  strokeControlOnNeutralRest: "var(--ctrl-stroke-control-on-neutral-rest, var(--smtc-stroke-control-on-neutral-rest, var(--colorNeutralStroke1)))",
  strokeControlOnNeutralHover: "var(--ctrl-stroke-control-on-neutral-hover, var(--smtc-stroke-control-on-neutral-hover, var(--colorNeutralStroke1Hover)))",
  strokeControlOnNeutralPressed: "var(--ctrl-stroke-control-on-neutral-pressed, var(--smtc-stroke-control-on-neutral-pressed, var(--colorNeutralStroke1Pressed)))",
  strokeControlOnNeutralDisabled: "var(--ctrl-stroke-control-on-neutral-disabled, var(--smtc-stroke-control-on-neutral-disabled, var(--colorNeutralStrokeDisabled)))",
  strokeControlOutlineRest: "var(--smtc-stroke-control-outline-rest, var(--colorNeutralStroke1))",
  strokeControlOutlineHover: "var(--smtc-stroke-control-outline-hover, var(--colorNeutralStroke1Hover))",
  strokeControlOutlinePressed: "var(--smtc-stroke-control-outline-pressed, var(--colorNeutralStroke1Pressed))",
  strokeControlOutlineDisabled: "var(--smtc-stroke-control-outline-disabled, var(--colorNeutralStrokeDisabled))",
  strokeWidthControlOutlineRest: "var(--smtc-stroke-width-default, var(--strokeWidthThin))",
  strokeWidthControlOutlineHover: "var(--smtc-stroke-width-default, var(--strokeWidthThin))",
  strokeWidthControlOutlinePressed: "var(--smtc-stroke-width-default, var(--strokeWidthThin))",
  controlFocusInnerStrokeColor: "var(--smtc-control-focus-inner-stroke-color, var(--colorStrokeFocus1))",
  controlFocusOuterStrokeColor: "var(--smtc-control-focus-outer-stroke-color, var(--colorStrokeFocus2))",
  nullColor: "var(--smtc-null-color, var(--colorTransparentBackground))",
  textStyleDefaultRegularFontFamily: "var(--smtc-text-style-default-regular-font-family, var(--fontFamilyBase))",
  textRampBody2FontSize: "var(--smtc-text-ramp-body-2-font-size, var(--fontSizeBase300))",
  textControlButtonWeight: "var(--ctrl-text-control-button-weight, var(--smtc-text-control-button-weight, var(--fontWeightSemibold)))",
  textRampBody2LineHeight: "var(--smtc-text-ramp-body-2-line-height, var(--lineHeightBase300))",
  paddingControlHorizontalDefault: "var(--smtc-padding-control-horizontal-default, var(--spacingHorizontalM))",
  gapControlDefault: "var(--smtc-gap-control-default, var(--spacingHorizontalSNudge))",
  controlFocusOuterStrokeWidth: "var(--smtc-control-focus-outer-stroke-width, var(--strokeWidthThick))",
  controlFocusInnerStrokeWidth: "var(--smtc-control-focus-inner-stroke-width, var(--strokeWidthThin))",
  cornerControlRest: "var(--smtc-corner-control-rest, var(--borderRadiusMedium))",
  cornerControlHover: "var(--smtc-corner-control-hover, var(--borderRadiusMedium))",
  cornerControlPressed: "var(--smtc-corner-control-pressed, var(--borderRadiusMedium))",
  cornerSmallControlRest: "var(--smtc-corner-small-control-rest, var(--borderRadiusSmall))",
  cornerSmallControlHover: "var(--smtc-corner-small-control-hover, var(--borderRadiusSmall))",
  cornerSmallControlPressed: "var(--smtc-corner-small-control-pressed, var(--borderRadiusSmall))",
  cornerLargeControlRest: "var(--smtc-corner-large-control-rest, var(--borderRadiusLarge))",
  cornerLargeControlHover: "var(--smtc-corner-large-control-hover, var(--borderRadiusLarge))",
  cornerLargeControlPressed: "var(--smtc-corner-large-control-pressed, var(--borderRadiusLarge))",
  cornerControlCircular: "var(--smtc-corner-control-circular, var(--borderRadiusCircular))",
  cornerControlNone: "var(--smtc-corner-control-none, var(--borderRadiusNone))",
  gapSmallControlDefault: "var(--smtc-gap-small-control-default, var(--spacingHorizontalXS))",
  paddingSmallControlVertical: "var(--smtc-padding-small-control-vertical, var(--spacingHorizontalS))",
  textRampCaption1FontSize: "var(--smtc-text-ramp-caption-1-font-size, var(--fontSizeBase200))",
  textRampCaption1LineHeight: "var(--smtc-text-ramp-caption-1-line-height, var(--lineHeightBase200))",
  textRampCaption1FontWeight: "var(--smtc-text-ramp-caption-1-font-weight, var(--fontWeightRegular))",
  paddingLargeControlVertical: "var(--smtc-padding-large-control-vertical, var(--spacingHorizontalL))",
  textRampBody3FontSize: "var(--smtc-text-ramp-body-3-font-size, var(--fontSizeBase400))",
  textRampBody3LineHeight: "var(--smtc-text-ramp-body-3-line-height, var(--lineHeightBase400))",
  textRampBody3FontWeight: "var(--smtc-text-ramp-body-3-font-weight, var(--fontWeightRegular))",
  curveControlStateTransition: "var(--smtc-curve-control-state-transition, var(--curveEasyEase))",
  durationControlStateTransition: "var(--smtc-duration-control-state-transition, var(--durationFaster))",
  strokeControlNoneRest: "var(--smtc-stroke-control-none-rest, var(--colorTransparentStroke))",
  strokeControlNoneHover: "var(--smtc-stroke-control-none-hover, var(--colorTransparentStroke))",
  strokeControlNonePressed: "var(--smtc-stroke-control-none-pressed, var(--colorTransparentStroke))",
  backgroundControlNeutralSelected: "var(--smtc-background-control-neutral-selected, var(--colorNeutralBackground1Selected))",
  strokeControlNoneSelected: "var(--smtc-stroke-control-none-selected, var(--colorTransparentStroke))",
  foregroundControlNeutralSelected: "var(--smtc-foreground-control-neutral-selected, var(--colorNeutralForeground1Selected))",
  backgroundControlBrandSelected: "var(--smtc-background-control-brand-selected, var(--colorBrandBackground1Selected))",
  foregroundControlOnBrandSelected: "var(--smtc-foreground-control-on-brand-selected, var(--colorNeutralForegroundOnBrand))",
  backgroundControlSubtleSelected: "var(--smtc-background-control-subtle-selected, var(--colorSubtleBackgroundSelected))",
  backgroundControlOutlineSelected: "var(--smtc-background-control-outline-selected, var(--colorTransparentBackgroundSelected))",
  
};