import { edgeBrandVariants } from './brandVariants.js';
import { type ColorTokens } from '@fluentui/tokens';

export declare interface PhoenixColorTokens {
  colorBrandForeground1Hover: string;
  colorBrandForeground1Pressed: string;
  colorBrandForeground1Selected: string;
  colorBrandForeground2Selected: string;
  colorBrandStroke: string;
  colorBrandStrokeHover: string;
  colorBrandStrokePressed: string;
  colorLabelBerry: string;
  colorLabelBlue: string;
  colorLabelBrass: string;
  colorLabelHotPink: string;
  colorLabelMink: string;
  colorLabelPumpkin: string;
  colorLabelPurple: string;
  colorLabelRoyalBlue: string;
  colorLabelTeal: string;
  colorLayerBackgroundApp: string;
  colorLayerBackgroundBase: string;
  colorLayerBackgroundDialog: string;
  colorLayerBackgroundTooltip: string;
  colorLayerBackgroundTooltipStaticInverted: string;
  colorLayerStrokeBase: string;
  colorLayerStrokeFlyout: string;
  colorNeutralBackgroundTabActive: string;
  colorNeutralForegroundDisabledOnBrand: string;
  colorNeutralForegroundHint: string;
  colorNeutralForegroundOnLabel: string;
  colorNeutralBackgroundFloating: string;
  colorNeutralBackgroundFloatingHover: string;
  colorNeutralBackgroundFloatingPressed: string;
  colorNeutralBackgroundFloatingSelected: string;
  colorNeutralBackgroundFloatingDisabled: string;
  colorAiFlair1: string;
  colorAiFlair2: string;
  colorAiFlair3: string;
  colorLayerBackgroundPillMenu: string;
  colorLayerOmniboxBackground: string;
  colorLayerOmniboxBackgroundHover: string;
}

export const lightThemeColors: PhoenixColorTokens = {
  colorBrandForeground1Hover: edgeBrandVariants[70],
  colorBrandForeground1Pressed: edgeBrandVariants[60],
  colorBrandForeground1Selected: edgeBrandVariants[80],
  colorBrandForeground2Selected: edgeBrandVariants[70],
  colorBrandStroke: edgeBrandVariants[80],
  colorBrandStrokeHover: edgeBrandVariants[70],
  colorBrandStrokePressed: edgeBrandVariants[60],
  colorLabelBerry: '#C239B3',
  colorLabelBlue: '#296EEB',
  colorLabelBrass: '#986F0B',
  colorLabelHotPink: '#E3008C',
  colorLabelMink: '#706D6B',
  colorLabelPumpkin: '#CA5010',
  colorLabelPurple: '#8230FF',
  colorLabelRoyalBlue: '#004E8C',
  colorLabelTeal: '#038387',
  colorLayerBackgroundApp: '#dde2e8',
  colorLayerBackgroundBase: '#FFFFFF80',
  colorLayerBackgroundDialog: '#FFFFFF',
  colorLayerBackgroundTooltip: '#FFFFFF',
  colorLayerBackgroundTooltipStaticInverted: '#333333',
  colorLayerStrokeBase: '#75757566',
  colorLayerStrokeFlyout: '#0000000F',
  colorNeutralBackgroundFloating: '#FFFFFF',
  colorNeutralBackgroundFloatingDisabled: '#F0F0F0',
  colorNeutralBackgroundFloatingHover: '#F5F5F5',
  colorNeutralBackgroundFloatingPressed: '#E0E0E0',
  colorNeutralBackgroundFloatingSelected: '#F0F0F0',
  colorNeutralBackgroundTabActive: '#FFFFFFD9',
  colorNeutralForegroundDisabledOnBrand: '#FFFFFF85',
  colorNeutralForegroundHint: '#0000008F',
  colorNeutralForegroundOnLabel: '#FFFFFF',
  colorAiFlair1: '#296EEB',
  colorAiFlair2: '#6CEBE2',
  colorAiFlair3: '#34CFA9',
  colorLayerBackgroundPillMenu: '#ffffff80',
  colorLayerOmniboxBackground: '#F1F3F6',
  colorLayerOmniboxBackgroundHover: '#EBEEF1',
};

export const lightThemeSolidColors: Partial<PhoenixColorTokens> = {
  colorLayerBackgroundBase: '#FAFAFA',
};

export const lightThemeColorOverrides: Partial<ColorTokens> = {
  colorBrandForeground2Pressed: edgeBrandVariants[40],
  colorNeutralBackground1: '#FFFFFFB3',
  colorNeutralBackground1Hover: '#0000000A',
  colorNeutralBackground1Pressed: '#0000001F',
  colorNeutralBackground1Selected: '#00000014',
  colorNeutralBackground2: '#00000005',
  colorNeutralBackground2Hover: '#0000000F',
  colorNeutralBackground2Pressed: '#00000024',
  colorNeutralBackground2Selected: '#00000019',
  colorNeutralBackground3: '#0000000A',
  colorNeutralBackground3Hover: '#00000014',
  colorNeutralBackground3Pressed: '#00000029',
  colorNeutralBackground3Selected: '#0000001F',
  colorNeutralBackground4: '#0000000F',
  colorNeutralBackground5: '#00000014',
  colorNeutralBackgroundDisabled: '#0000000F',
  colorNeutralForeground1: '#000000DB',
  colorNeutralForeground1Hover: '#000000DB',
  colorNeutralForeground1Pressed: '#000000DB',
  colorNeutralForeground1Selected: '#000000DB',
  colorNeutralForeground2: '#000000BD',
  colorNeutralForeground2Hover: '#000000DB',
  colorNeutralForeground2Pressed: '#000000DB',
  colorNeutralForeground2Selected: '#000000DB',
  colorNeutralForeground3: '#0000009e',
  colorNeutralForeground3Hover: '#0000009e',
  colorNeutralForeground3Pressed: '#0000009e',
  colorNeutralForeground3Selected: '#0000009e',
  colorNeutralForeground4: '#0000008F',
  colorNeutralForegroundDisabled: '#00000042',
  colorNeutralForegroundInvertedDisabled: '#FFFFFF66',
  colorNeutralForegroundStaticInverted: '#FFFFFF',
  colorNeutralStroke1: '#0000002E',
  colorNeutralStroke1Hover: '#00000038',
  colorNeutralStroke1Pressed: '#0000004C',
  colorNeutralStroke1Selected: '#00000042',
  colorNeutralStroke2: '#0000001F',
  colorNeutralStroke3: '#0000000F',
  colorNeutralStrokeAccessible: '#0000009E',
  colorNeutralStrokeAccessibleHover: '#000000A8',
  colorNeutralStrokeAccessiblePressed: '#000000B2',
  colorNeutralStrokeDisabled: '#0000001F',
  colorNeutralStrokeInvertedDisabled: '#FFFFFF66',
  colorNeutralStrokeOnBrand: '#FFFFFF',
  colorNeutralStrokeOnBrand2: '#FFFFFF',
  colorNeutralStrokeOnBrand2Hover: '#FFFFFF',
  colorNeutralStrokeOnBrand2Pressed: '#FFFFFF',
  colorNeutralStrokeOnBrand2Selected: '#FFFFFF',
  colorStrokeFocus1: '#FFFFFF',
  colorSubtleBackground: '#00000000',
  colorSubtleBackgroundHover: '#0000000A',
  colorSubtleBackgroundPressed: '#00000006',
  colorSubtleBackgroundSelected: '#00000014',
  colorNeutralCardBackground: '#FFFFFF',
  colorNeutralCardBackgroundHover: '#FAFAFA',
};

export const darkThemeColors: PhoenixColorTokens = {
  colorBrandForeground1Hover: edgeBrandVariants[120],
  colorBrandForeground1Pressed: edgeBrandVariants[130],
  colorBrandForeground1Selected: edgeBrandVariants[110],
  colorBrandForeground2Selected: edgeBrandVariants[120],
  colorBrandStroke: edgeBrandVariants[110],
  colorBrandStrokeHover: edgeBrandVariants[120],
  colorBrandStrokePressed: edgeBrandVariants[130],
  colorLabelBerry: '#CF87DA',
  colorLabelBlue: '#69A1FA',
  colorLabelBrass: '#C1A256',
  colorLabelHotPink: '#EE5FB7',
  colorLabelMink: '#84817E',
  colorLabelPumpkin: '#DF8E64',
  colorLabelPurple: '#B696FF',
  colorLabelRoyalBlue: '#4A89BA',
  colorLabelTeal: '#4CB4B7',
  colorLayerBackgroundApp: '#000',
  colorLayerBackgroundBase: '#3A3A3A4D',
  colorLayerBackgroundDialog: '#292929',
  colorLayerBackgroundTooltip: '#292929',
  colorLayerBackgroundTooltipStaticInverted: '#3D3D3D',
  colorLayerStrokeBase: '#75757566',
  colorLayerStrokeFlyout: '#00000033',
  colorNeutralBackgroundTabActive: '#FFFFFF22',
  colorNeutralForegroundDisabledOnBrand: '#FFFFFF3D',
  colorNeutralForegroundHint: '#FFFFFF85',
  colorNeutralForegroundOnLabel: '#000000e5',
  colorNeutralBackgroundFloating: '#292929',
  colorNeutralBackgroundFloatingHover: '#3D3D3D',
  colorNeutralBackgroundFloatingPressed: '#1F1F1F',
  colorNeutralBackgroundFloatingSelected: '#1F1F1F',
  colorNeutralBackgroundFloatingDisabled: '#141414',
  colorAiFlair1: '#4D8DFA',
  colorAiFlair2: '#6CEBE2',
  colorAiFlair3: '#34CFA9',
  colorLayerBackgroundPillMenu: '#2C2C2C',
  colorLayerOmniboxBackground: '#0E0E0E',
  colorLayerOmniboxBackgroundHover: '#000000',
};

export const darkThemeSolidColors: Partial<PhoenixColorTokens> = {
  colorLayerBackgroundBase: '#1F1F1F',
};

export const darkThemeColorOverrides: Partial<ColorTokens> = {
  colorBrandBackground2: edgeBrandVariants[40],
  colorBrandForeground1: edgeBrandVariants[110],
  colorBrandForeground2: edgeBrandVariants[120],
  colorBrandForeground2Pressed: edgeBrandVariants[110],
  colorBrandForegroundLink: edgeBrandVariants[110],
  colorBrandForegroundLinkHover: edgeBrandVariants[120],
  colorBrandForegroundLinkSelected: edgeBrandVariants[110],
  colorNeutralBackground1: '#FFFFFF0B',
  colorNeutralBackground1Hover: '#FFFFFF22',
  colorNeutralBackground1Pressed: '#FFFFFF00',
  colorNeutralBackground1Selected: '#FFFFFF1C',
  colorNeutralBackground2: '#3A3A3A4D',
  colorNeutralBackground2Hover: '#3A3A3ABF',
  colorNeutralBackground2Pressed: '#3A3A3A57',
  colorNeutralBackground2Selected: '#3A3A3AC9',
  colorNeutralBackground3: '#3A3A3A4D',
  colorNeutralBackground3Hover: '#3A3A3AB3',
  colorNeutralBackground3Pressed: '#3A3A3A2E',
  colorNeutralBackground3Selected: '#3A3A3A9E',
  colorNeutralBackground4: '#3A3A3A2E',
  colorNeutralBackgroundDisabled: '#3A3A3A4D',
  colorNeutralForeground1: '#FFFFFF',
  colorNeutralForeground1Hover: '#FFFFFF',
  colorNeutralForeground1Pressed: '#FFFFFF',
  colorNeutralForeground1Selected: '#FFFFFF',
  colorNeutralForeground2: '#FFFFFFD6',
  colorNeutralForeground2Hover: '#FFFFFF',
  colorNeutralForeground2Pressed: '#FFFFFF',
  colorNeutralForeground2Selected: '#FFFFFF',
  colorNeutralForeground3: '#FFFFFFAD',
  colorNeutralForeground3Hover: '#FFFFFFD6',
  colorNeutralForeground3Pressed: '#FFFFFFD6',
  colorNeutralForeground3Selected: '#FFFFFFD6',
  colorNeutralForeground4: '#FFFFFF85',
  colorNeutralForegroundDisabled: '#FFFFFF3D',
  colorNeutralForegroundInvertedDisabled: '#FFFFFF66',
  colorNeutralForegroundStaticInverted: '#FFFFFF',
  colorNeutralStroke1: '#FFFFFF49',
  colorNeutralStroke1Hover: '#FFFFFF75',
  colorNeutralStroke1Pressed: '#FFFFFF6B',
  colorNeutralStroke1Selected: '#FFFFFF70',
  colorNeutralStroke2: '#FFFFFF31',
  colorNeutralStroke3: '#FFFFFF3D',
  colorNeutralStrokeAccessible: '#FFFFFF',
  colorNeutralStrokeAccessibleHover: '#FFFFFF',
  colorNeutralStrokeAccessiblePressed: '#FFFFFF',
  colorNeutralStrokeDisabled: '#FFFFFF42',
  colorNeutralStrokeOnBrand2: '#FFFFFF',
  colorNeutralStrokeOnBrand2Hover: '#FFFFFF',
  colorNeutralStrokeOnBrand2Pressed: '#FFFFFF',
  colorNeutralStrokeOnBrand2Selected: '#FFFFFF',
  colorStrokeFocus2: '#FFFFFF',
  colorSubtleBackground: '#FFFFFF00',
  colorSubtleBackgroundHover: '#FFFFFF10',
  colorSubtleBackgroundPressed: '#FFFFFF0B',
  colorSubtleBackgroundSelected: '#FFFFFF22',
};

export declare interface KumoColorTokens {
  backgroundControlBrandHover: string;
  backgroundControlBrandPressed: string;
  backgroundControlBrandRest: string;
  backgroundControlBrandSelected: string;
  backgroundControlNeutralDisabled: string;
  backgroundControlNeutralHover: string;
  backgroundControlNeutralPressed: string;
  backgroundControlNeutralRest: string;
  backgroundControlNeutralSelected: string;
  backgroundControlOutlineDisabled: string;
  backgroundControlOutlineHover: string;
  backgroundControlOutlinePressed: string;
  backgroundControlOutlineRest: string;
  backgroundControlOutlineSelected: string;
  backgroundControlSubtleHover: string;
  backgroundControlSubtlePressed: string;
  backgroundControlSubtleRest: string;
  backgroundControlSubtleSelected: string;
  controlFocusOuterStrokeColor: string;
  controlFocusInnerStrokeColor: string;
  foregroundControlNeutralPrimaryDisabled: string;
  foregroundControlNeutralPrimaryHover: string;
  foregroundControlNeutralPrimaryPressed: string;
  foregroundControlNeutralPrimaryRest: string;
  foregroundControlOnBrandRest: string;
  foregroundControlOnOutlineDisabled: string;
  foregroundControlOnOutlineHover: string;
  foregroundControlOnOutlinePressed: string;
  foregroundControlOnOutlineRest: string;
  nullColor0: string;
  nullColor3: string;
  strokeControlNoneHover: string;
  strokeControlNonePressed: string;
  strokeControlNoneRest: string;
  strokeControlNoneSelected: string;
  strokeControlOnNeutralDisabled: string;
  strokeControlOutlineDisabled: string;
  strokeControlOutlineHover: string;
  strokeControlOutlinePressed: string;
  strokeControlOutlineRest: string;
  strokeControlOutlineSelected: string;
}

export const kumoLightThemeColors: KumoColorTokens = {
  backgroundControlBrandHover: '#282C30',
  backgroundControlBrandPressed: '#3A3D42',
  backgroundControlBrandRest: '#23272B',
  backgroundControlBrandSelected: '#23272B',
  backgroundControlNeutralDisabled: '#EAEFF5',
  backgroundControlNeutralHover: '#EAEFF5',
  backgroundControlNeutralPressed: '#D3D8DE',
  backgroundControlNeutralRest: '#F6F9FC',
  backgroundControlNeutralSelected: '#DDE2E8',
  backgroundControlOutlineDisabled: 'transparent',
  backgroundControlOutlineHover: 'transparent',
  backgroundControlOutlinePressed: 'transparent',
  backgroundControlOutlineRest: 'transparent',
  backgroundControlOutlineSelected: 'transparent',
  backgroundControlSubtleHover: '#EDF2F9',
  backgroundControlSubtlePressed: '#DADEE5',
  backgroundControlSubtleRest: 'transparent',
  backgroundControlSubtleSelected: '#E3E8EF',
  controlFocusOuterStrokeColor: '#000000',
  controlFocusInnerStrokeColor: '#FFFFFF',
  foregroundControlNeutralPrimaryDisabled: '#B3B8BE',
  foregroundControlNeutralPrimaryHover: '#23272B',
  foregroundControlNeutralPrimaryPressed: '#23272B',
  foregroundControlNeutralPrimaryRest: '#23272B',
  foregroundControlOnBrandRest: '#FFFFFF',
  foregroundControlOnOutlineDisabled: '#B3B8BE',
  foregroundControlOnOutlineHover: '#474B50',
  foregroundControlOnOutlinePressed: '#474B50',
  foregroundControlOnOutlineRest: '#474B50',
  nullColor0: 'transparent',
  nullColor3: 'transparent',
  strokeControlNoneHover: 'transparent',
  strokeControlNonePressed: 'transparent',
  strokeControlNoneSelected: 'transparent',
  strokeControlNoneRest: 'transparent',
  strokeControlOnNeutralDisabled: '#DADEE5',
  strokeControlOutlineDisabled: '#DADEE5',
  strokeControlOutlineHover: '#BDC1C7',
  strokeControlOutlinePressed: '#A7ABB1',
  strokeControlOutlineRest: '#C6CBD1',
  strokeControlOutlineSelected: '#C6CBD1',
};

export const kumoDarkThemeColors: KumoColorTokens = {
  backgroundControlBrandHover: '#EAEFF5',
  backgroundControlBrandPressed: '#D3D8DE',
  backgroundControlBrandRest: '#F6F9FC',
  backgroundControlBrandSelected: '#F6F9FC',
  backgroundControlNeutralDisabled: '#111418',
  backgroundControlNeutralHover: '#2D3135',
  backgroundControlNeutralPressed: '#3F4348',
  backgroundControlNeutralRest: '#26292E',
  backgroundControlNeutralSelected: '#282C30',
  backgroundControlOutlineDisabled: 'transparent',
  backgroundControlOutlineHover: 'transparent',
  backgroundControlOutlinePressed: 'transparent',
  backgroundControlOutlineRest: 'transparent',
  backgroundControlOutlineSelected: 'transparent',
  backgroundControlSubtleHover: '#26292E',
  backgroundControlSubtlePressed: '#35383D',
  backgroundControlSubtleRest: 'transparent',
  backgroundControlSubtleSelected: '#2D3135',
  controlFocusOuterStrokeColor: '#FFFFFF',
  controlFocusInnerStrokeColor: '#000000',
  foregroundControlNeutralPrimaryDisabled: '#52565B',
  foregroundControlNeutralPrimaryHover: '#FFFFFF',
  foregroundControlNeutralPrimaryPressed: '#FFFFFF',
  foregroundControlNeutralPrimaryRest: '#FFFFFF',
  foregroundControlOnBrandRest: '#23272B',
  foregroundControlOnOutlineDisabled: '#52565B',
  foregroundControlOnOutlineHover: '#FFFFFF',
  foregroundControlOnOutlinePressed: '#FFFFFF',
  foregroundControlOnOutlineRest: '#FFFFFF',
  nullColor0: 'transparent',
  nullColor3: 'transparent',
  strokeControlNoneHover: 'transparent',
  strokeControlNonePressed: 'transparent',
  strokeControlNoneSelected: 'transparent',
  strokeControlNoneRest: 'transparent',
  strokeControlOnNeutralDisabled: '#3A3D42',
  strokeControlOutlineDisabled: '#3A3D42',
  strokeControlOutlineHover: '#686C72',
  strokeControlOutlinePressed: '#5F6469',
  strokeControlOutlineRest: '#5A5E63',
  strokeControlOutlineSelected: '#5A5E63',
};
