import {
  alphaBlack,
  alphaWhite,
  neutral,
  shadow,
  statusDanger,
  statusSuccess,
  statusWarning,
  vibrant,
} from './globalColors.js';

import type {
  ThemeBackgroundColors,
  ThemeForegroundColors,
  ThemeMaterialColors,
  ThemeNullColors,
  ThemeShadowColors,
  ThemeStatusColors,
  ThemeStrokeColors,
} from './themeColors.js';

export const darkNullColors: ThemeNullColors = {
  nullColor: alphaBlack[0],
  nullColorBackground: '{nullColor}',
  nullColorBackgroundHover: '{nullColor}',
  nullColorBackgroundPressed: '{nullColor}',
  nullColorStroke: '{nullColor}',
};

export const darkBackgroundColors: ThemeBackgroundColors = {
  backgroundCardOnflyoutDefaultDisabled: neutral[0],
  backgroundCardOnflyoutDefaultHover: neutral[0],
  backgroundCardOnflyoutDefaultPressed: neutral[0],
  backgroundCardOnflyoutDefaultRest: neutral[0],
  backgroundCardOnprimaryAltDisabled: neutral[650],
  backgroundCardOnprimaryAltHover: vibrant[800],
  backgroundCardOnprimaryAltPressed: vibrant[700],
  backgroundCardOnprimaryAltRest: vibrant[900],
  backgroundCardOnprimaryDefaultDisabled: neutral[650],
  backgroundCardOnprimaryDefaultHover: neutral[804],
  backgroundCardOnprimaryDefaultPressed: neutral[808],
  backgroundCardOnprimaryDefaultRest: neutral[800],
  backgroundCardOnprimaryDefaultSelected: neutral[700],
  backgroundCardOnsecondaryAltDisabled: neutral[0],
  backgroundCardOnsecondaryAltHover: neutral[0],
  backgroundCardOnsecondaryAltPressed: neutral[0],
  backgroundCardOnsecondaryAltRest: neutral[0],
  backgroundCardOnsecondaryDefaultDisabled: neutral[0],
  backgroundCardOnsecondaryDefaultHover: neutral[0],
  backgroundCardOnsecondaryDefaultPressed: neutral[0],
  backgroundCardOnsecondaryDefaultRest: neutral[0],
  backgroundControlBrandRest: '{backgroundCtrlBrandRest}',
  backgroundControlInputRest: '{ctrlInputBackgroundRest}',
  backgroundControlNeutralHover: '{backgroundCtrlNeutralHover}',
  backgroundControlNeutralRest: '{backgroundCtrlNeutralRest}',
  backgroundControlProgressBarEmptyRest: '{ctrlProgressBackgroundEmpty}',
  backgroundControlSubtleDisabled: '{backgroundCtrlSubtleDisabled}',
  backgroundControlSubtleHover: '{backgroundCtrlSubtleHover}',
  backgroundControlSubtlePressed: '{backgroundCtrlSubtlePressed}',
  backgroundControlSubtleRest: '{backgroundCtrlSubtleRest}',
  backgroundCtrlActivebrandDisabled: '{backgroundCtrlBrandDisabled}',
  backgroundCtrlActivebrandHover: '{backgroundCtrlBrandHover}',
  backgroundCtrlActivebrandPressed: '{backgroundCtrlBrandPressed}',
  backgroundCtrlActivebrandRest: '{backgroundCtrlBrandRest}',
  backgroundCtrlBrandDisabled: neutral[650],
  backgroundCtrlBrandHover: neutral[104],
  backgroundCtrlBrandPressed: neutral[108],
  backgroundCtrlBrandRest: neutral[100],
  backgroundCtrlNeutralDisabled: neutral[650],
  backgroundCtrlNeutralHover: neutral[704],
  backgroundCtrlNeutralPressed: neutral[708],
  backgroundCtrlNeutralRest: neutral[700],
  backgroundCtrlOnimageHover: alphaBlack[50],
  backgroundCtrlOnimagePressed: alphaBlack[40],
  backgroundCtrlOnimageRest: alphaBlack[60],
  backgroundCtrlOutlineDisabled: '{nullColor}',
  backgroundCtrlOutlineHover: '{nullColor}',
  backgroundCtrlOutlinePressed: '{nullColor}',
  backgroundCtrlOutlineRest: '{nullColor}',
  backgroundCtrlShapesafeActivebrandDisabled: '{foregroundCtrlBrandDisabled}',
  backgroundCtrlShapesafeActivebrandRest: '{foregroundCtrlBrandRest}',
  backgroundCtrlShapesafeNeutralDisabled:
    '{foregroundCtrlNeutralPrimaryDisabled}',
  backgroundCtrlShapesafeNeutralHover: '{backgroundCtrlShapesafeNeutralRest}',
  backgroundCtrlShapesafeNeutralPressed: '{backgroundCtrlShapesafeNeutralRest}',
  backgroundCtrlShapesafeNeutralRest: neutral[450],
  backgroundCtrlSubtleDisabled: '{backgroundCtrlSubtleRest}',
  backgroundCtrlSubtleHover: neutral[704],
  backgroundCtrlSubtleHoverSplit: '{nullColor}',
  backgroundCtrlSubtlePressed: neutral[708],
  backgroundCtrlSubtleRest: alphaBlack[0],
  backgroundFlyoutColorblend: neutral[800],
  backgroundFlyoutLumblend: neutral[800],
  backgroundFlyoutSolid: neutral[800],
  backgroundLayerPrimarySolid: neutral[800],
  backgroundLayerPrimaryStop1: neutral[800],
  backgroundLayerPrimaryStop2: neutral[800],
  backgroundLayerPrimaryStop3: neutral[800],
  backgroundLayerSecondary: neutral[750],
  backgroundLayerTertiary: neutral[750],
  backgroundSmoke: alphaBlack[40],
  backgroundToolbar: '{backgroundCardOnprimaryDefaultRest}',
  backgroundWebPagePrimary: neutral[800],
  backgroundWebPageSecondary: neutral[800],
  backgroundWindowPrimaryColorBlend: neutral[800],
  backgroundWindowPrimaryLumBlend: neutral[800],
  backgroundWindowPrimarySolid: neutral[800],
  backgroundWindowSecondaryColorBlend: neutral[0],
  backgroundWindowSecondaryLumBlend: neutral[0],
  backgroundWindowSecondarySolid: neutral[0],
  backgroundWindowTabBandColorBlend: neutral[1000],
  backgroundWindowTabBandInactive: neutral[800],
  backgroundWindowTabBandLumBlend: neutral[1000],
  backgroundWindowTabBandSolid: neutral[1000],
};

export const darkStrokeColors: ThemeStrokeColors = {
  strokeCardOnprimaryDisabled: '{nullColor}',
  strokeCardOnprimaryHover: '{nullColor}',
  strokeCardOnprimaryPressed: '{nullColor}',
  strokeCardOnprimaryRest: '{nullColor}',
  strokeCardOnSecondaryDisabled: '{nullColor}',
  strokeCardOnSecondaryHover: '{nullColor}',
  strokeCardOnSecondaryPressed: '{nullColor}',
  strokeCardOnSecondaryRest: '{nullColor}',
  strokeCardSelected: '{nullColor}',
  strokeCtrlDividerOnActivebrand: '{strokeCtrlDividerOnBrand}',
  strokeCtrlDividerOnActivebrandDisabled: '{strokeCtrlDividerOnBrandDisabled}',
  strokeCtrlDividerOnBrand: alphaBlack[0],
  strokeCtrlDividerOnBrandDisabled: '{nullColor}',
  strokeCtrlDividerOnneutral: alphaBlack[0],
  strokeCtrlDividerOnneutralDisabled: '{nullColor}',
  strokeCtrlDividerOnoutline: alphaBlack[0],
  strokeCtrlDividerOnoutlineDisabled: '{nullColor}',
  strokeCtrlDividerOnSubtle: '{nullColor}',
  strokeCtrlDividerOnSubtleDisabled: '{nullColor}',
  strokeCtrlOnactivebrandDisabled: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnactivebrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnactivebrandHover: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnactivebrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnactivebrandPressed: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnactivebrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnactivebrandRest: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnactivebrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnBrandDisabled: '{nullColor}',
  strokeCtrlOnBrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnBrandHover: '{nullColor}',
  strokeCtrlOnBrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnBrandPressed: '{nullColor}',
  strokeCtrlOnBrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnBrandRest: '{nullColor}',
  strokeCtrlOnBrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnneutralDisabled: '{nullColor}',
  strokeCtrlOnneutralDisabledStop2: '{strokeCtrlOnneutralDisabled}',
  strokeCtrlOnneutralHover: '{nullColor}',
  strokeCtrlOnneutralHoverStop2: '{strokeCtrlOnneutralHover}',
  strokeCtrlOnneutralPressed: '{nullColor}',
  strokeCtrlOnneutralPressedStop2: '{strokeCtrlOnneutralPressed}',
  strokeCtrlOnneutralRest: '{nullColor}',
  strokeCtrlOnneutralRestStop2: '{strokeCtrlOnneutralRest}',
  strokeCtrlOnoutlineDisabled: neutral[550],
  strokeCtrlOnoutlineDisabledStop2: '{strokeCtrlOnoutlineDisabled}',
  strokeCtrlOnoutlineHover: neutral[554],
  strokeCtrlOnoutlineHoverStop2: '{strokeCtrlOnoutlineHover}',
  strokeCtrlOnoutlinePressed: neutral[558],
  strokeCtrlOnoutlinePressedStop2: '{strokeCtrlOnoutlinePressed}',
  strokeCtrlOnoutlineRest: neutral[550],
  strokeCtrlOnoutlineRestStop2: '{strokeCtrlOnoutlineRest}',
  strokeCtrlOnsubtleDisabled: '{nullColor}',
  strokeCtrlOnsubtleHover: '{nullColor}',
  strokeCtrlOnsubtleHoverSplit: '{nullColor}',
  strokeCtrlOnsubtlePressed: '{nullColor}',
  strokeCtrlOnsubtleRest: '{nullColor}',
  strokeDividerBrand: '{backgroundCtrlBrandRest}',
  strokeDividerDefault: neutral[550],
  strokeDividerStrong: '{strokeDividerDefault}',
  strokeDividerSubtle: neutral[650],
  strokeFlyout: '{nullColor}',
  strokeImage: '{nullColor}',
  strokeLayer: '{nullColor}',
  strokeToolbar: '{nullColor}',
  strokeWindowActive: alphaBlack[0],
  strokeWindowInactive: '{strokeWindowActive}',
};

export const darkForegroundColors: ThemeForegroundColors = {
  foregroundContentBrandPrimary: '{foregroundCtrlBrandRest}',
  foregroundContentNeutralPrimary: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundContentNeutralSecondary: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundControlBrandRest: '{foregroundCtrlBrandRest}',
  foregroundControlIconOnSubtleDisabled: '{foregroundCtrlIconOnsubtleDisabled}',
  foregroundControlIconOnSubtleHover: '{foregroundCtrlIconOnsubtleHover}',
  foregroundControlIconOnSubtlePressed: '{foregroundCtrlIconOnsubtlePressed}',
  foregroundControlIconOnSubtleRest: '{foregroundCtrlIconOnsubtleRest}',
  foregroundControlLinkBrandRest: '{ctrlLinkForegroundBrandRest}',
  foregroundControlNeutralPrimaryRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundControlNeutralSecondaryDisabled:
    '{foregroundCtrlNeutralSecondaryDisabled}',
  foregroundControlNeutralSecondaryHover:
    '{foregroundCtrlNeutralSecondaryHover}',
  foregroundControlNeutralSecondaryPressed:
    '{foregroundCtrlNeutralSecondaryPressed}',
  foregroundControlNeutralSecondaryRest: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundControlOnActiveBrandRest: '{foregroundCtrlOnactivebrandRest}',
  foregroundControlOnBrandRest: '{foregroundCtrlOnbrandRest}',
  foregroundControlShapesafeNeutralHover: '{foregroundCtrlNeutralPrimaryHover}',
  foregroundControlShapeSafeNeutralHover:
    '{foregroundControlShapesafeNeutralHover}',
  foregroundControlShapeSafeNeutralPressed:
    '{foregroundControlShapesafeNeutralPressed}',
  foregroundControlShapesafeNeutralPressed:
    '{foregroundCtrlNeutralPrimaryPressed}',
  foregroundControlShapesafeNeutralRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlActivebrandDisabled: '{foregroundCtrlBrandDisabled}',
  foregroundCtrlActivebrandHover: '{foregroundCtrlBrandHover}',
  foregroundCtrlActivebrandPressed: '{foregroundCtrlBrandPressed}',
  foregroundCtrlActivebrandRest: '{foregroundCtrlBrandRest}',
  foregroundCtrlBrandDisabled: neutral[500],
  foregroundCtrlBrandHover: neutral[100],
  foregroundCtrlBrandPressed: neutral[100],
  foregroundCtrlBrandRest: neutral[100],
  foregroundCtrlHintDefault: neutral[550],
  foregroundCtrlIconOnneutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnneutralHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnneutralPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnneutralRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnoutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnoutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnoutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnoutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnsubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnsubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnsubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnsubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryDisabled: neutral[500],
  foregroundCtrlNeutralPrimaryHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryRest: neutral[0],
  foregroundCtrlNeutralSecondaryDisabled: neutral[500],
  foregroundCtrlNeutralSecondaryHover: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryPressed: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryRest: neutral[400],
  foregroundCtrlOnactivebrandDisabled: '{foregroundCtrlOnbrandDisabled}',
  foregroundCtrlOnactivebrandHover: '{foregroundCtrlOnbrandRest}',
  foregroundCtrlOnactivebrandPressed: '{foregroundCtrlOnbrandRest}',
  foregroundCtrlOnactivebrandRest: '{foregroundCtrlOnbrandRest}',
  foregroundCtrlOnbrandDisabled: neutral[500],
  foregroundCtrlOnbrandHover: '{foregroundCtrlOnbrandRest}',
  foregroundCtrlOnbrandPressed: '{foregroundCtrlOnbrandRest}',
  foregroundCtrlOnbrandRest: neutral[800],
  foregroundCtrlOnimageRest: neutral[0],
  foregroundCtrlOnoutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOnoutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnoutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnoutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnsubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOnsubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnsubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnsubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOntransparentDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOntransparentHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOntransparentPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOntransparentRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundNeutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundNeutralSecondary: '{foregroundCtrlNeutralSecondaryRest}',
};

export const darkShadowColors: ThemeShadowColors = {
  shadowToolbarKeyColor: shadow.shadowKeyLowDark,
  shadowToolbarAmbientColor: shadow.shadowAmbientLowDark,
  shadowWindowActiveKeyColor: shadow.shadowKeyHighDark,
  shadowWindowActiveAmbientColor: shadow.shadowAmbientHighDark,
  shadowWindowInactiveKeyColor: shadow.shadowKeyHighDark,
  shadowWindowInactiveAmbientColor: shadow.shadowAmbientHighDark,
  shadowCardRestKeyColor: '{nullColor}',
  shadowCardRestAmbientColor: '{nullColor}',
  shadowCardHoverKeyColor: '{nullColor}',
  shadowCardPressedKeyColor: '{nullColor}',
  shadowCardDisabledKeyColor: '{nullColor}',
  shadowFlyoutKeyColor: shadow.shadowKeyLowDark,
  shadowFlyoutAmbientColor: shadow.shadowAmbientLowDark,
  shadowCtrlOnDragKeyColor: '{shadowFlyoutKeyColor}',
  shadowCtrlOnDragAmbientColor: '{shadowFlyoutAmbientColor}',
  shadowLayerKeyColor: shadow.shadowKeyHighDark,
  shadowLayerAmbientColor: shadow.shadowAmbientHighDark,
};

export const darkMaterialColors: ThemeMaterialColors = {
  materialAcrylicDefaultColorblend: '{nullColor}',
  materialAcrylicDefaultLumblend: '{nullColor}',
  materialAcrylicDefaultSolid: neutral[800],
  materialAcrylicShellDefaultColorblend: neutral[0],
  materialAcrylicShellDefaultLumblend: neutral[0],
  materialAcrylicShellDefaultSolid: neutral[0],
  materialMicaDarkerColorblend: neutral[0],
  materialMicaDarkerLumblend: neutral[0],
  materialMicaDarkerSolid: neutral[0],
  materialMicaDefaultColorblend: neutral[0],
  materialMicaDefaultLumblend: neutral[0],
  materialMicaDefaultSolid: neutral[0],
  materialMicaThinColorblend: neutral[0],
  materialMicaThinLumblend: neutral[0],
  materialMicaThinSolid: neutral[0],
};

export const darkStatusColors: ThemeStatusColors = {
  statusBrandBackground: vibrant[400],
  statusBrandForeground: neutral[800],
  statusBrandStroke: vibrant[500],
  statusBrandTintBackground: vibrant[900],
  statusBrandTintForeground: vibrant[400],
  statusBrandTintStroke: alphaBlack[0],
  statusDangerBackground: statusDanger[400],
  statusDangerForeground: neutral[800],
  statusDangerStroke: statusDanger[500],
  statusDangerTintBackground: statusDanger[900],
  statusDangerTintForeground: statusDanger[400],
  statusDangerTintStroke: alphaBlack[0],
  statusSuccessBackground: statusSuccess[400],
  statusSuccessForeground: neutral[800],
  statusSuccessStroke: statusSuccess[500],
  statusSuccessTintBackground: statusSuccess[900],
  statusSuccessTintForeground: statusSuccess[400],
  statusSuccessTintStroke: alphaBlack[0],
  statusWarningBackground: statusWarning[400],
  statusWarningForeground: neutral[800],
  statusWarningStroke: statusWarning[500],
  statusWarningTintBackground: statusWarning[900],
  statusWarningTintForeground: statusWarning[400],
  statusWarningTintStroke: alphaBlack[0],
  statusInformativeBackground: vibrant[900],
  statusInformativeForeground: neutral[350],
  statusInformativeStroke: '{nullColor}',
  statusInformativeTintBackground: neutral[700],
  statusInformativeTintForeground: neutral[0],
  statusInformativeTintStroke: alphaBlack[0],
  statusImportantBackground: '{nullColor}',
  statusImportantForeground: '{nullColor}',
  statusImportantStroke: alphaWhite[0],
  statusImportantTintBackground: alphaBlack[0],
  statusImportantTintForeground: alphaBlack[0],
  statusImportantTintStroke: alphaBlack[0],
  statusAwayForeground: '#e47700', // Kumo vibrant.orange.400
  statusOofForeground: '#be74e1', // Kumo vibrant.purple.400
};
