import {
  alphaBlack,
  alphaWhite,
  neutral,
  shadow,
  statusDanger,
  statusSuccess,
  statusWarning,
  vibrant,
} from './globalColors.js';

import type {
  ThemeBackgroundColors,
  ThemeForegroundColors,
  ThemeMaterialColors,
  ThemeNullColors,
  ThemeShadowColors,
  ThemeStatusColors,
  ThemeStrokeColors,
} from './themeColors.js';

export const darkNullColors: ThemeNullColors = {
  nullColor: alphaBlack[0],
  nullColorBackground: '{nullColor}',
};

export const darkBackgroundColors: ThemeBackgroundColors = {
  backgroundCtrlBrandRest: neutral[100],
  backgroundCtrlBrandHover: neutral[104],
  backgroundCtrlBrandPressed: neutral[108],
  backgroundCtrlBrandDisabled: neutral[650],
  backgroundCtrlActivebrandRest: '{backgroundCtrlBrandRest}',
  backgroundCtrlActivebrandHover: '{backgroundCtrlBrandHover}',
  backgroundCtrlActivebrandPressed: '{backgroundCtrlBrandPressed}',
  backgroundCtrlActivebrandDisabled: '{backgroundCtrlBrandDisabled}',
  backgroundCtrlNeutralRest: neutral[700],
  backgroundCtrlNeutralHover: neutral[704],
  backgroundCtrlNeutralPressed: neutral[708],
  backgroundCtrlNeutralDisabled: neutral[650],
  backgroundCtrlSubtleRest: alphaBlack[0],
  backgroundCtrlSubtleHover: neutral[704],
  backgroundCtrlSubtlePressed: neutral[708],
  backgroundCtrlSubtleDisabled: '{backgroundCtrlSubtleRest}',
  backgroundCtrlSubtleHoverSplit: '{nullColor}',
  backgroundCtrlOutlineRest: '{nullColor}',
  backgroundCtrlOutlineHover: '{nullColor}',
  backgroundCtrlOutlinePressed: '{nullColor}',
  backgroundCtrlOutlineDisabled: '{nullColor}',
  backgroundCtrlOnImageRest: alphaBlack[60],
  backgroundCtrlOnImageHover: alphaBlack[50],
  backgroundCtrlOnImagePressed: alphaBlack[40],
  backgroundCtrlShapesafeNeutralRest: neutral[450],
  backgroundCtrlShapesafeNeutralHover: '{backgroundCtrlShapesafeNeutralRest}',
  backgroundCtrlShapesafeNeutralPressed: '{backgroundCtrlShapesafeNeutralRest}',
  backgroundCtrlShapesafeNeutralDisabled:
    '{foregroundCtrlNeutralPrimaryDisabled}',
  backgroundCtrlShapesafeActivebrandRest: '{foregroundCtrlBrandRest}',
  backgroundCtrlShapesafeActivebrandDisabled: '{foregroundCtrlBrandDisabled}',
  backgroundControlProgressBarEmptyRest: '{ctrlProgressBackgroundEmpty}',
  backgroundCardOnPrimaryDefaultRest: neutral[800],
  backgroundCardOnPrimaryDefaultHover: neutral[804],
  backgroundCardOnPrimaryDefaultPressed: neutral[808],
  backgroundCardOnPrimaryDefaultDisabled: neutral[650],
  backgroundCardOnPrimaryDefaultSelected: neutral[700],
  backgroundCardOnPrimaryAltRest: vibrant[900],
  backgroundCardOnPrimaryAltHover: vibrant[800],
  backgroundCardOnPrimaryAltPressed: vibrant[700],
  backgroundCardOnPrimaryAltDisabled: neutral[650],
  backgroundCardOnSecondaryDefaultRest: neutral[0],
  backgroundCardOnSecondaryDefaultHover: neutral[0],
  backgroundCardOnSecondaryDefaultPressed: neutral[0],
  backgroundCardOnSecondaryDefaultDisabled: neutral[0],
  backgroundCardOnSecondaryAltRest: neutral[0],
  backgroundCardOnSecondaryAltHover: neutral[0],
  backgroundCardOnSecondaryAltPressed: neutral[0],
  backgroundCardOnSecondaryAltDisabled: neutral[0],
  backgroundCardOnFlyoutDefaultRest: neutral[0],
  backgroundCardOnFlyoutDefaultHover: neutral[0],
  backgroundCardOnFlyoutDefaultPressed: neutral[0],
  backgroundCardOnFlyoutDefaultDisabled: neutral[0],
  backgroundWebPagePrimary: neutral[800],
  backgroundWebPageSecondary: neutral[800],
  backgroundFlyoutSolid: neutral[800],
  backgroundFlyoutLumBlend: neutral[800],
  backgroundFlyoutColorBlend: neutral[800],
  backgroundToolbar: '{backgroundCardOnPrimaryDefaultRest}',
  backgroundLayerPrimarySolid: neutral[800],
  backgroundLayerPrimaryStop1: neutral[800],
  backgroundLayerPrimaryStop2: neutral[800],
  backgroundLayerPrimaryStop3: neutral[800],
  backgroundLayerSecondary: neutral[750],
  backgroundLayerTertiary: neutral[750],
  backgroundWindowTabBandSolid: neutral[1000],
  backgroundWindowTabBandInactive: neutral[800],
  backgroundWindowTabBandLumBlend: neutral[1000],
  backgroundWindowTabBandColorBlend: neutral[1000],
  backgroundWindowPrimarySolid: neutral[800],
  backgroundWindowPrimaryLumBlend: neutral[800],
  backgroundWindowPrimaryColorBlend: neutral[800],
  backgroundWindowSecondarySolid: neutral[0],
  backgroundWindowSecondaryLumBlend: neutral[0],
  backgroundWindowSecondaryColorBlend: neutral[0],
  backgroundSmoke: alphaBlack[40],
};

export const darkStrokeColors: ThemeStrokeColors = {
  strokeCardOnprimaryDisabled: '{nullColor}',
  strokeCardOnprimaryHover: '{nullColor}',
  strokeCardOnprimaryPressed: '{nullColor}',
  strokeCardOnprimaryRest: '{nullColor}',
  strokeCardOnSecondaryDisabled: '{nullColor}',
  strokeCardOnSecondaryHover: '{nullColor}',
  strokeCardOnSecondaryPressed: '{nullColor}',
  strokeCardOnSecondaryRest: '{nullColor}',
  strokeCardSelected: '{nullColor}',
  strokeCtrlDividerOnActivebrand: '{strokeCtrlDividerOnBrand}',
  strokeCtrlDividerOnActivebrandDisabled: '{strokeCtrlDividerOnBrandDisabled}',
  strokeCtrlDividerOnBrand: alphaBlack[0],
  strokeCtrlDividerOnBrandDisabled: '{nullColor}',
  strokeCtrlDividerOnneutral: alphaBlack[0],
  strokeCtrlDividerOnneutralDisabled: '{nullColor}',
  strokeCtrlDividerOnOutline: alphaBlack[0],
  strokeCtrlDividerOnOutlineDisabled: '{nullColor}',
  strokeCtrlDividerOnSubtle: '{nullColor}',
  strokeCtrlDividerOnSubtleDisabled: '{nullColor}',
  strokeCtrlOnactivebrandDisabled: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnactivebrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnactivebrandHover: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnactivebrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnactivebrandPressed: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnactivebrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnactivebrandRest: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnactivebrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnBrandDisabled: '{nullColor}',
  strokeCtrlOnBrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnBrandHover: '{nullColor}',
  strokeCtrlOnBrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnBrandPressed: '{nullColor}',
  strokeCtrlOnBrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnBrandRest: '{nullColor}',
  strokeCtrlOnBrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnneutralDisabled: '{nullColor}',
  strokeCtrlOnneutralDisabledStop2: '{strokeCtrlOnneutralDisabled}',
  strokeCtrlOnneutralHover: '{nullColor}',
  strokeCtrlOnneutralHoverStop2: '{strokeCtrlOnneutralHover}',
  strokeCtrlOnneutralPressed: '{nullColor}',
  strokeCtrlOnneutralPressedStop2: '{strokeCtrlOnneutralPressed}',
  strokeCtrlOnneutralRest: '{nullColor}',
  strokeCtrlOnneutralRestStop2: '{strokeCtrlOnneutralRest}',
  strokeCtrlOnoutlineDisabled: neutral[550],
  strokeCtrlOnoutlineDisabledStop2: '{strokeCtrlOnOutlineDisabled}',
  strokeCtrlOnoutlineHover: neutral[554],
  strokeCtrlOnoutlineHoverStop2: '{strokeCtrlOnOutlineHover}',
  strokeCtrlOnoutlinePressed: neutral[558],
  strokeCtrlOnoutlinePressedStop2: '{strokeCtrlOnOutlinePressed}',
  strokeCtrlOnoutlineRest: neutral[550],
  strokeCtrlOnoutlineRestStop2: '{strokeCtrlOnOutlineRest}',
  strokeCtrlOnsubtleDisabled: '{nullColor}',
  strokeCtrlOnsubtleHover: '{nullColor}',
  strokeCtrlOnsubtleHoverSplit: '{nullColor}',
  strokeCtrlOnsubtlePressed: '{nullColor}',
  strokeCtrlOnsubtleRest: '{nullColor}',
  strokeDividerBrand: '{backgroundCtrlBrandRest}',
  strokeDividerDefault: neutral[550],
  strokeDividerStrong: '{strokeDividerDefault}',
  strokeDividerSubtle: neutral[650],
  strokeFlyout: '{nullColor}',
  strokeImage: '{nullColor}',
  strokeLayer: '{nullColor}',
  strokeToolbar: '{nullColor}',
  strokeWindowActive: alphaBlack[0],
  strokeWindowInactive: '{strokeWindowActive}',
};

export const darkForegroundColors: ThemeForegroundColors = {
  foregroundCtrlNeutralPrimaryRest: neutral[0],
  foregroundCtrlNeutralPrimaryHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryDisabled: neutral[500],
  foregroundCtrlNeutralSecondaryRest: neutral[400],
  foregroundCtrlNeutralSecondaryHover: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryPressed: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryDisabled: neutral[500],
  foregroundCtrlOnOutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOnSubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOntransparentRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOntransparentHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOntransparentPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOntransparentDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnneutralRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnneutralHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnneutralPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnneutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnOutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnSubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlBrandRest: neutral[100],
  foregroundCtrlBrandHover: neutral[100],
  foregroundCtrlBrandPressed: neutral[100],
  foregroundCtrlBrandDisabled: neutral[500],
  foregroundCtrlActivebrandRest: '{foregroundCtrlBrandRest}',
  foregroundCtrlActivebrandHover: '{foregroundCtrlBrandHover}',
  foregroundCtrlActivebrandPressed: '{foregroundCtrlBrandPressed}',
  foregroundCtrlActivebrandDisabled: '{foregroundCtrlBrandDisabled}',
  foregroundCtrlOnBrandRest: neutral[800],
  foregroundCtrlOnBrandHover: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnBrandPressed: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnBrandDisabled: neutral[500],
  foregroundCtrlOnActivebrandRest: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActivebrandHover: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActivebrandPressed: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActivebrandDisabled: '{foregroundCtrlOnBrandDisabled}',
  foregroundCtrlHintDefault: neutral[550],
  foregroundCtrlOnImageRest: neutral[0],
  foregroundControlShapeSafeNeutralRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundControlShapeSafeNeutralHover: '{foregroundCtrlNeutralPrimaryHover}',
  foregroundControlShapeSafeNeutralPressed:
    '{foregroundCtrlNeutralPrimaryPressed}',
  foregroundControlOnBrandRest: '{foregroundCtrlOnBrandRest}',
  foregroundControlLinkBrandRest: '{ctrlLinkForegroundBrandRest}',
  foregroundContentNeutralPrimary: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundContentNeutralSecondary: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundContentBrandPrimary: '{foregroundCtrlBrandRest}',
  foregroundNeutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
};

export const darkShadowColors: ThemeShadowColors = {
  shadowToolbarKeyColor: shadow.shadowKeyLowDark,
  shadowToolbarAmbientColor: shadow.shadowAmbientLowDark,
  shadowWindowActiveKeyColor: shadow.shadowKeyHighDark,
  shadowWindowActiveAmbientColor: shadow.shadowAmbientHighDark,
  shadowWindowInactiveKeyColor: shadow.shadowKeyHighDark,
  shadowWindowInactiveAmbientColor: shadow.shadowAmbientHighDark,
  shadowCardRestKeyColor: '{nullColor}',
  shadowCardRestAmbientColor: '{nullColor}',
  shadowCardHoverKeyColor: '{nullColor}',
  shadowCardPressedKeyColor: '{nullColor}',
  shadowCardDisabledKeyColor: '{nullColor}',
  shadowFlyoutKeyColor: shadow.shadowKeyLowDark,
  shadowFlyoutAmbientColor: shadow.shadowAmbientLowDark,
  shadowCtrlOnDragKeyColor: '{shadowFlyoutKeyColor}',
  shadowCtrlOnDragAmbientColor: '{shadowFlyoutAmbientColor}',
  shadowLayerKeyColor: shadow.shadowKeyHighDark,
  shadowLayerAmbientColor: shadow.shadowAmbientHighDark,
};

export const darkMaterialColors: ThemeMaterialColors = {
  materialAcrylicDefaultSolid: neutral[800],
  materialAcrylicDefaultColorBlend: '{nullColor}',
  materialAcrylicDefaultLumBlend: '{nullColor}',
  materialAcrylicShellDefaultSolid: neutral[0],
  materialAcrylicShellDefaultColorBlend: neutral[0],
  materialAcrylicShellDefaultLumBlend: neutral[0],
  materialMicaThinSolid: neutral[0],
  materialMicaThinColorBlend: neutral[0],
  materialMicaThinLumBlend: neutral[0],
  materialMicaDarkerSolid: neutral[0],
  materialMicaDarkerColorBlend: neutral[0],
  materialMicaDarkerLumBlend: neutral[0],
  materialMicaDefaultSolid: neutral[0],
  materialMicaDefaultColorBlend: neutral[0],
  materialMicaDefaultLumBlend: neutral[0],
};

export const darkStatusColors: ThemeStatusColors = {
  statusBrandBackground: vibrant[400],
  statusBrandForeground: neutral[800],
  statusBrandStroke: vibrant[500],
  statusBrandTintBackground: vibrant[900],
  statusBrandTintForeground: vibrant[400],
  statusBrandTintStroke: alphaBlack[0],
  statusDangerBackground: statusDanger[400],
  statusDangerForeground: neutral[800],
  statusDangerStroke: statusDanger[500],
  statusDangerTintBackground: statusDanger[900],
  statusDangerTintForeground: statusDanger[400],
  statusDangerTintStroke: alphaBlack[0],
  statusSuccessBackground: statusSuccess[400],
  statusSuccessForeground: neutral[800],
  statusSuccessStroke: statusSuccess[500],
  statusSuccessTintBackground: statusSuccess[900],
  statusSuccessTintForeground: statusSuccess[400],
  statusSuccessTintStroke: alphaBlack[0],
  statusWarningBackground: statusWarning[400],
  statusWarningForeground: neutral[800],
  statusWarningStroke: statusWarning[500],
  statusWarningTintBackground: statusWarning[900],
  statusWarningTintForeground: statusWarning[400],
  statusWarningTintStroke: alphaBlack[0],
  statusInformativeBackground: vibrant[900],
  statusInformativeForeground: neutral[350],
  statusInformativeStroke: '{nullColor}',
  statusInformativeTintBackground: neutral[700],
  statusInformativeTintForeground: neutral[0],
  statusInformativeTintStroke: alphaBlack[0],
  statusImportantBackground: '{nullColor}',
  statusImportantForeground: '{nullColor}',
  statusImportantStroke: alphaWhite[0],
  statusImportantTintBackground: alphaBlack[0],
  statusImportantTintForeground: alphaBlack[0],
  statusImportantTintStroke: alphaBlack[0],
  statusAwayForeground: '#e47700', // Kumo vibrant.orange.400
  statusOofForeground: '#be74e1', // Kumo vibrant.purple.400
};
