import {
  alphaBlack,
  alphaWhite,
  neutral,
  shadow,
  statusDanger,
  statusSuccess,
  statusWarning,
  vibrant,
} from './globalColors.js';

import type {
  ThemeBackgroundColors,
  ThemeForegroundColors,
  ThemeMaterialColors,
  ThemeNullColors,
  ThemeShadowColors,
  ThemeStatusColors,
  ThemeStrokeColors,
} from './themeColors.js';

export const darkNullColors: ThemeNullColors = {
  nullColor: alphaBlack[0],
};

export const darkBackgroundColors: ThemeBackgroundColors = {
  backgroundCtrlBrandRest: neutral[750],
  backgroundCtrlBrandHover: neutral[754],
  backgroundCtrlBrandPressed: neutral[758],
  backgroundCtrlBrandDisabled: neutral[200],
  backgroundActiveBrandRest: neutral[750],
  backgroundActiveBrandHover: neutral[754],
  backgroundActiveBrandPressed: neutral[758],
  backgroundActiveBrandDisabled: neutral[200],
  backgroundNeutralRest: neutral[150],
  backgroundNeutralHover: neutral[154],
  backgroundNeutralPressed: neutral[158],
  backgroundNeutralDisabled: neutral[200],
  backgroundSubtleRest: alphaWhite[0],
  backgroundSubtleHover: neutral[4],
  backgroundSubtlePressed: neutral[8],
  backgroundSubtleDisabled: alphaWhite[0],
  backgroundSubtleHoverSplit: '{nullColor}',
  backgroundOutlineRest: '{nullColor}',
  backgroundOutlineHover: '{nullColor}',
  backgroundOutlinePressed: '{nullColor}',
  backgroundOutlineDisabled: '{nullColor}',
  backgroundOnImageRest: alphaBlack[60],
  backgroundOnImageHover: alphaBlack[50],
  backgroundOnImagePressed: alphaBlack[40],
  backgroundShapeSafeNeutralRest: neutral[400],
  backgroundShapeSafeNeutralHover: '{backgroundShapeSafeNeutralRest}',
  backgroundShapeSafeNeutralPressed: '{backgroundShapeSafeNeutralRest}',
  backgroundShapeSafeNeutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  backgroundShapeSafeActiveBrandRest: '{foregroundCtrlBrandRest}',
  backgroundShapeSafeActiveBrandDisabled: '{foregroundCtrlBrandDisabled}',
  backgroundCardOnPrimaryDefaultRest: neutral[0],
  backgroundCardOnPrimaryDefaultHover: neutral[4],
  backgroundCardOnPrimaryDefaultPressed: neutral[8],
  backgroundCardOnPrimaryDefaultDisabled: neutral[200],
  backgroundCardOnPrimaryDefaultSelected: neutral[150],
  backgroundCardOnPrimaryAltRest: vibrant[100],
  backgroundCardOnPrimaryAltHover: vibrant[200],
  backgroundCardOnPrimaryAltPressed: vibrant[300],
  backgroundCardOnPrimaryAltDisabled: neutral[200],
  backgroundCardOnSecondaryDefaultRest: neutral[0],
  backgroundCardOnSecondaryDefaultHover: neutral[0],
  backgroundCardOnSecondaryDefaultPressed: neutral[0],
  backgroundCardOnSecondaryDefaultDisabled: neutral[0],
  backgroundCardOnSecondaryAltRest: neutral[0],
  backgroundCardOnSecondaryAltHover: neutral[0],
  backgroundCardOnSecondaryAltPressed: neutral[0],
  backgroundCardOnSecondaryAltDisabled: neutral[0],
  backgroundCardOnFlyoutDefaultRest: neutral[0],
  backgroundCardOnFlyoutDefaultHover: neutral[0],
  backgroundCardOnFlyoutDefaultPressed: neutral[0],
  backgroundCardOnFlyoutDefaultDisabled: neutral[0],
  backgroundWebPagePrimary: neutral[0],
  backgroundWebPageSecondary: neutral[0],
  backgroundFlyoutSolid: neutral[0],
  backgroundFlyoutLumBlend: neutral[0],
  backgroundFlyoutColorBlend: neutral[0],
  backgroundToolbar: '{backgroundCardOnPrimaryDefaultRest}',
  backgroundLayerPrimarySolid: neutral[0],
  backgroundLayerPrimaryStop1: neutral[0],
  backgroundLayerPrimaryStop2: neutral[0],
  backgroundLayerPrimaryStop3: neutral[0],
  backgroundLayerSecondary: neutral[100],
  backgroundLayerTertiary: neutral[100],
  backgroundWindowTabBandSolid: neutral[250],
  backgroundWindowTabBandInactive: neutral[200],
  backgroundWindowLumBlend: neutral[0],
  backgroundWindowColorBlend: neutral[0],
  backgroundWindowPrimarySolid: neutral[0],
  backgroundWindowPrimaryLumBlend: neutral[0],
  backgroundWindowPrimaryColorBlend: neutral[0],
  backgroundWindowSecondarySolid: neutral[0],
  backgroundWindowSecondaryLumBlend: neutral[0],
  backgroundWindowSecondaryColorBlend: neutral[0],
  backgroundSmoke: alphaBlack[30],
};

export const darkStrokeColors: ThemeStrokeColors = {
  strokeDividerDefault: neutral[300],
  strokeDividerSubtle: neutral[200],
  strokeDividerBrand: '{backgroundCtrlBrandRest}',
  strokeDividerStrong: '{strokeDividerDefault}',
  strokeCtrlOnActiveBrandRest: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnActiveBrandHover: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnActiveBrandPressed: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnActiveBrandDisabled: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnActiveBrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnActiveBrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnActiveBrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnActiveBrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnBrandRest: '{nullColor}',
  strokeCtrlOnBrandHover: '{nullColor}',
  strokeCtrlOnBrandPressed: '{nullColor}',
  strokeCtrlOnBrandDisabled: '{nullColor}',
  strokeCtrlOnBrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnBrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnBrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnBrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnNeutralRest: '{nullColor}',
  strokeCtrlOnNeutralHover: '{nullColor}',
  strokeCtrlOnNeutralPressed: '{nullColor}',
  strokeCtrlOnNeutralDisabled: '{nullColor}',
  strokeCtrlOnNeutralRestStop2: '{strokeCtrlOnNeutralRest}',
  strokeCtrlOnNeutralHoverStop2: '{strokeCtrlOnNeutralHover}',
  strokeCtrlOnNeutralPressedStop2: '{strokeCtrlOnNeutralPressed}',
  strokeCtrlOnNeutralDisabledStop2: '{strokeCtrlOnNeutralDisabled}',
  strokeCtrlOnOutlineRest: neutral[300],
  strokeCtrlOnOutlineHover: neutral[304],
  strokeCtrlOnOutlinePressed: neutral[308],
  strokeCtrlOnOutlineDisabled: neutral[200],
  strokeCtrlOnOutlineRestStop2: '{strokeCtrlOnOutlineRest}',
  strokeCtrlOnOutlineHoverStop2: '{strokeCtrlOnOutlineHover}',
  strokeCtrlOnOutlinePressedStop2: '{strokeCtrlOnOutlinePressed}',
  strokeCtrlOnOutlineDisabledStop2: '{strokeCtrlOnOutlineDisabled}',
  strokeCtrlOnSubtleRest: '{nullColor}',
  strokeCtrlOnSubtleHover: '{nullColor}',
  strokeCtrlOnSubtlePressed: '{nullColor}',
  strokeCtrlOnSubtleDisabled: '{nullColor}',
  strokeCtrlOnSubtleHoverSplit: '{nullColor}',
  strokeToolbar: '{nullColor}',
  strokeImage: '{nullColor}',
  strokeCardOnPrimaryRest: '{nullColor}',
  strokeCardOnPrimaryHover: '{nullColor}',
  strokeCardOnPrimaryPressed: '{nullColor}',
  strokeCardOnPrimaryDisabled: '{nullColor}',
  strokeCardOnSecondaryRest: '{nullColor}',
  strokeCardOnSecondaryHover: '{nullColor}',
  strokeCardOnSecondaryPressed: '{nullColor}',
  strokeCardOnSecondaryDisabled: '{nullColor}',
  strokeCardSelected: '{nullColor}',
  strokeFlyout: '{nullColor}',
  strokeLayer: '{nullColor}',
  strokeWindowActive: alphaWhite[0],
  strokeWindowInactive: '{strokeWindowActive}',
};

export const darkForegroundColors: ThemeForegroundColors = {
  foregroundCtrlNeutralPrimaryRest: neutral[800],
  foregroundCtrlNeutralPrimaryHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryDisabled: neutral[350],
  foregroundCtrlNeutralSecondaryRest: neutral[450],
  foregroundCtrlNeutralSecondaryHover: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryPressed: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryDisabled: neutral[350],
  foregroundCtrlOnOutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOnSubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOnTransparentRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnTransparentHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnTransparentPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnTransparentDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnNeutralRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnNeutralHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnNeutralPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnNeutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnOutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnSubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlBrandRest: neutral[750],
  foregroundCtrlBrandHover: neutral[750],
  foregroundCtrlBrandPressed: neutral[750],
  foregroundCtrlBrandDisabled: neutral[350],
  foregroundCtrlActiveBrandRest: '{foregroundCtrlBrandRest}',
  foregroundCtrlActiveBrandHover: '{foregroundCtrlBrandHover}',
  foregroundCtrlActiveBrandPressed: '{foregroundCtrlBrandPressed}',
  foregroundCtrlActiveBrandDisabled: '{foregroundCtrlBrandDisabled}',
  foregroundCtrlOnBrandRest: neutral[0],
  foregroundCtrlOnBrandHover: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnBrandPressed: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnBrandDisabled: neutral[350],
  foregroundCtrlOnActiveBrandRest: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActiveBrandHover: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActiveBrandPressed: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActiveBrandDisabled: '{foregroundCtrlOnBrandDisabled}',
  foregroundCtrlHintDefault: neutral[300],
  foregroundCtrlOnImageRest: neutral[0],
  foregroundContentNeutralPrimary: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundContentNeutralSecondary: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundContentBrandPrimary: '{foregroundCtrlBrandRest}',
};

export const darkShadowColors: ThemeShadowColors = {
  shadowToolbarKeyColor: shadow.shadowKeyLowLight,
  shadowToolbarAmbientColor: shadow.shadowAmbientLowLight,
  shadowWindowActiveKeyColor: shadow.shadowKeyHighLight,
  shadowWindowActiveAmbientColor: shadow.shadowAmbientHighLight,
  shadowWindowInactiveKeyColor: shadow.shadowKeyHighLight,
  shadowWindowInactiveAmbientColor: shadow.shadowAmbientHighLight,
  shadowCardRestKeyColor: '{nullColor}',
  shadowCardRestAmbientColor: '{nullColor}',
  shadowCardHoverKeyColor: '{nullColor}',
  shadowCardPressedKeyColor: '{nullColor}',
  shadowCardDisabledKeyColor: '{nullColor}',
  shadowFlyoutKeyColor: shadow.shadowKeyLowLight,
  shadowFlyoutAmbientColor: shadow.shadowAmbientLowLight,
  shadowCtrlOnDragKeyColor: '{shadowFlyoutKeyColor}',
  shadowCtrlOnDragAmbientColor: '{shadowFlyoutAmbientColor}',
  shadowLayerKeyColor: shadow.shadowKeyHighLight,
  shadowLayerAmbientColor: shadow.shadowAmbientHighLight,
};

export const darkMaterialColors: ThemeMaterialColors = {
  materialAcrylicDefaultSolid: neutral[0],
  materialAcrylicDefaultColorBlend: '{nullColor}',
  materialAcrylicDefaultLumBlend: '{nullColor}',
  materialAcrylicShellDefaultSolid: neutral[0],
  materialAcrylicShellDefaultColorBlend: neutral[0],
  materialAcrylicShellDefaultLumBlend: neutral[0],
  materialMicaThinSolid: neutral[0],
  materialMicaThinColorBlend: neutral[0],
  materialMicaThinLumBlend: neutral[0],
  materialMicaDarkerSolid: neutral[0],
  materialMicaDarkerColorBlend: neutral[0],
  materialMicaDarkerLumBlend: neutral[0],
  materialMicaDefaultSolid: neutral[0],
  materialMicaDefaultColorBlend: neutral[0],
  materialMicaDefaultLumBlend: neutral[0],
};

export const darkStatusColors: ThemeStatusColors = {
  statusBrandBackground: vibrant[600],
  statusBrandForeground: neutral[0],
  statusBrandStroke: vibrant[500],
  statusBrandTintBackground: vibrant[100],
  statusBrandTintForeground: vibrant[600],
  statusBrandTintStroke: alphaWhite[0],
  statusDangerBackground: statusDanger[600],
  statusDangerForeground: neutral[0],
  statusDangerStroke: statusDanger[500],
  statusDangerTintBackground: statusDanger[100],
  statusDangerTintForeground: statusDanger[600],
  statusDangerTintStroke: alphaWhite[0],
  statusSuccessBackground: statusSuccess[600],
  statusSuccessForeground: neutral[0],
  statusSuccessStroke: statusSuccess[500],
  statusSuccessTintBackground: statusSuccess[100],
  statusSuccessTintForeground: statusSuccess[600],
  statusSuccessTintStroke: alphaWhite[0],
  statusWarningBackground: statusWarning[600],
  statusWarningForeground: neutral[0],
  statusWarningStroke: statusWarning[500],
  statusWarningTintBackground: statusWarning[100],
  statusWarningTintForeground: statusWarning[600],
  statusWarningTintStroke: alphaWhite[0],
  statusInformativeBackground: vibrant[100],
  statusInformativeForeground: neutral[500],
  statusInformativeStroke: '{nullColor}',
  statusInformativeTintBackground: neutral[150],
  statusInformativeTintForeground: neutral[800],
  statusInformativeTintStroke: alphaWhite[0],
  statusImportantBackground: '{nullColor}',
  statusImportantForeground: '{nullColor}',
  statusImportantStroke: alphaWhite[0],
  statusImportantTintBackground: alphaWhite[0],
  statusImportantTintForeground: alphaWhite[0],
  statusImportantTintStroke: alphaWhite[0],
  statusAwayForeground: '#c85d00', // Kumo vibrant.orange.600
  statusOofForeground: '#8a42ab', // Kumo vibrant.purple.600
};
