export {
  type NeutralColors,
  type VibrantColors,
  type AlphaBlackColors,
  type AlphaWhiteColors,
  type AlphaVibrant100Colors,
  type AlphaVibrant800Colors,
  type ShadowColors,
  type StatusDangerColors,
  type StatusWarningColors,
  type StatusSuccessColors,
  neutral,
  vibrant,
  alphaBlack,
  alphaWhite,
  alphaVibrant100,
  alphaVibrant800,
  shadow,
  statusDanger,
  statusWarning,
  statusSuccess,
} from './globalColors.js';
