import { alphaBlack, alphaWhite, neutral, vibrant } from './globalColors.js';

export const lightNullColors: ThemeNullColors = {
  nullColor: alphaWhite[0],
};

export const lightBackgroundColors: ThemeBackgroundColors = {
  backgroundCtrlBrandRest: neutral[750],
  backgroundCtrlBrandHover: neutral[754],
  backgroundCtrlBrandPressed: neutral[758],
  backgroundCtrlBrandDisabled: neutral[200],
  backgroundActiveBrandRest: neutral[750],
  backgroundActiveBrandHover: neutral[754],
  backgroundActiveBrandPressed: neutral[758],
  backgroundActiveBrandDisabled: neutral[200],
  backgroundNeutralRest: neutral[150],
  backgroundNeutralHover: neutral[154],
  backgroundNeutralPressed: neutral[158],
  backgroundNeutralDisabled: neutral[200],
  backgroundSubtleRest: alphaWhite[0],
  backgroundSubtleHover: neutral[4],
  backgroundSubtlePressed: neutral[8],
  backgroundSubtleDisabled: alphaWhite[0],
  backgroundSubtleHoverSplit: '{nullColor}',
  backgroundOutlineRest: '{nullColor}',
  backgroundOutlineHover: '{nullColor}',
  backgroundOutlinePressed: '{nullColor}',
  backgroundOutlineDisabled: '{nullColor}',
  backgroundOnImageRest: alphaBlack[60],
  backgroundOnImageHover: alphaBlack[50],
  backgroundOnImagePressed: alphaBlack[40],
  backgroundShapeSafeNeutralRest: neutral[400],
  backgroundShapeSafeNeutralHover: '{backgroundShapeSafeNeutralRest}',
  backgroundShapeSafeNeutralPressed: '{backgroundShapeSafeNeutralRest}',
  backgroundShapeSafeNeutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  backgroundShapeSafeActiveBrandRest: '{foregroundCtrlBrandRest}',
  backgroundShapeSafeActiveBrandDisabled: '{foregroundCtrlBrandDisabled}',
  backgroundCardOnPrimaryDefaultRest: neutral[0],
  backgroundCardOnPrimaryDefaultHover: neutral[4],
  backgroundCardOnPrimaryDefaultPressed: neutral[8],
  backgroundCardOnPrimaryDefaultDisabled: neutral[200],
  backgroundCardOnPrimaryDefaultSelected: neutral[150],
  backgroundCardOnPrimaryAltRest: vibrant[100],
  backgroundCardOnPrimaryAltHover: vibrant[200],
  backgroundCardOnPrimaryAltPressed: vibrant[300],
  backgroundCardOnPrimaryAltDisabled: neutral[200],
  backgroundCardOnSecondaryDefaultRest: neutral[0],
  backgroundCardOnSecondaryDefaultHover: neutral[0],
  backgroundCardOnSecondaryDefaultPressed: neutral[0],
  backgroundCardOnSecondaryDefaultDisabled: neutral[0],
  backgroundCardOnSecondaryAltRest: neutral[0],
  backgroundCardOnSecondaryAltHover: neutral[0],
  backgroundCardOnSecondaryAltPressed: neutral[0],
  backgroundCardOnSecondaryAltDisabled: neutral[0],
  backgroundCardOnFlyoutDefaultRest: neutral[0],
  backgroundCardOnFlyoutDefaultHover: neutral[0],
  backgroundCardOnFlyoutDefaultPressed: neutral[0],
  backgroundCardOnFlyoutDefaultDisabled: neutral[0],
  backgroundWebPagePrimary: neutral[0],
  backgroundWebPageSecondary: neutral[0],
  backgroundFlyoutSolid: neutral[0],
  backgroundFlyoutLumBlend: neutral[0],
  backgroundFlyoutColorBlend: neutral[0],
  backgroundToolbar: '{backgroundCardOnPrimaryDefaultRest}',
  backgroundLayerPrimarySolid: neutral[0],
  backgroundLayerPrimaryStop1: neutral[0],
  backgroundLayerPrimaryStop2: neutral[0],
  backgroundLayerPrimaryStop3: neutral[0],
  backgroundLayerSecondary: neutral[100],
  backgroundLayerTertiary: neutral[100],
  backgroundWindowTabBandSolid: neutral[250],
  backgroundWindowTabBandInactive: neutral[200],
  backgroundWindowLumBlend: neutral[0],
  backgroundWindowColorBlend: neutral[0],
  backgroundWindowPrimarySolid: neutral[0],
  backgroundWindowPrimaryLumBlend: neutral[0],
  backgroundWindowPrimaryColorBlend: neutral[0],
  backgroundWindowSecondarySolid: neutral[0],
  backgroundWindowSecondaryLumBlend: neutral[0],
  backgroundWindowSecondaryColorBlend: neutral[0],
  backgroundSmoke: alphaBlack[30],
};

export const lightStrokeColors: ThemeStrokeColors = {
  strokeDividerDefault: neutral[300],
  strokeDividerSubtle: neutral[200],
  strokeDividerBrand: '{backgroundCtrlBrandRest}',
  strokeDividerStrong: '{strokeDividerDefault}',
  strokeCtrlOnActiveBrandRest: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnActiveBrandHover: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnActiveBrandPressed: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnActiveBrandDisabled: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnActiveBrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnActiveBrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnActiveBrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnActiveBrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnBrandRest: '{nullColor}',
  strokeCtrlOnBrandHover: '{nullColor}',
  strokeCtrlOnBrandPressed: '{nullColor}',
  strokeCtrlOnBrandDisabled: '{nullColor}',
  strokeCtrlOnBrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnBrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnBrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnBrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnNeutralRest: '{nullColor}',
  strokeCtrlOnNeutralHover: '{nullColor}',
  strokeCtrlOnNeutralPressed: '{nullColor}',
  strokeCtrlOnNeutralDisabled: '{nullColor}',
  strokeCtrlOnNeutralRestStop2: '{strokeCtrlOnNeutralRest}',
  strokeCtrlOnNeutralHoverStop2: '{strokeCtrlOnNeutralHover}',
  strokeCtrlOnNeutralPressedStop2: '{strokeCtrlOnNeutralPressed}',
  strokeCtrlOnNeutralDisabledStop2: '{strokeCtrlOnNeutralDisabled}',
  strokeCtrlOnOutlineRest: neutral[300],
  strokeCtrlOnOutlineHover: neutral[304],
  strokeCtrlOnOutlinePressed: neutral[308],
  strokeCtrlOnOutlineDisabled: neutral[200],
  strokeCtrlOnOutlineRestStop2: '{strokeCtrlOnOutlineRest}',
  strokeCtrlOnOutlineHoverStop2: '{strokeCtrlOnOutlineHover}',
  strokeCtrlOnOutlinePressedStop2: '{strokeCtrlOnOutlinePressed}',
  strokeCtrlOnOutlineDisabledStop2: '{strokeCtrlOnOutlineDisabled}',
  strokeCtrlOnSubtleRest: '{nullColor}',
  strokeCtrlOnSubtleHover: '{nullColor}',
  strokeCtrlOnSubtlePressed: '{nullColor}',
  strokeCtrlOnSubtleDisabled: '{nullColor}',
  strokeCtrlOnSubtleHoverSplit: '{nullColor}',
  strokeToolbar: '{nullColor}',
  strokeImage: '{nullColor}',
  strokeCardOnPrimaryRest: '{nullColor}',
  strokeCardOnPrimaryHover: '{nullColor}',
  strokeCardOnPrimaryPressed: '{nullColor}',
  strokeCardOnPrimaryDisabled: '{nullColor}',
  strokeCardOnSecondaryRest: '{nullColor}',
  strokeCardOnSecondaryHover: '{nullColor}',
  strokeCardOnSecondaryPressed: '{nullColor}',
  strokeCardOnSecondaryDisabled: '{nullColor}',
  strokeCardSelected: '{nullColor}',
  strokeFlyout: '{nullColor}',
  strokeLayer: '{nullColor}',
  strokeWindowActive: alphaWhite[0],
  strokeWindowInactive: '{strokeWindowActive}',
};

export const lightForegroundColors: ThemeForegroundColors = {
  foregroundCtrlNeutralPrimaryRest: neutral[800],
  foregroundCtrlNeutralPrimaryHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryDisabled: neutral[350],
  foregroundCtrlNeutralSecondaryRest: neutral[450],
  foregroundCtrlNeutralSecondaryHover: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryPressed: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryDisabled: neutral[350],
  foregroundCtrlOnOutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOnSubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOnTransparentRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnTransparentHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnTransparentPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnTransparentDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnNeutralRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnNeutralHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnNeutralPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnNeutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnOutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnSubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlBrandRest: neutral[750],
  foregroundCtrlBrandHover: neutral[750],
  foregroundCtrlBrandPressed: neutral[750],
  foregroundCtrlBrandDisabled: neutral[350],
  foregroundCtrlActiveBrandRest: '{foregroundCtrlBrandRest}',
  foregroundCtrlActiveBrandHover: '{foregroundCtrlBrandHover}',
  foregroundCtrlActiveBrandPressed: '{foregroundCtrlBrandPressed}',
  foregroundCtrlActiveBrandDisabled: '{foregroundCtrlBrandDisabled}',
  foregroundCtrlOnBrandRest: neutral[0],
  foregroundCtrlOnBrandHover: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnBrandPressed: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnBrandDisabled: neutral[350],
  foregroundCtrlOnActiveBrandRest: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActiveBrandHover: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActiveBrandPressed: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActiveBrandDisabled: '{foregroundCtrlOnBrandDisabled}',
  foregroundCtrlHintDefault: neutral[300],
  foregroundCtrlOnImageRest: neutral[0],
  foregroundContentNeutralPrimary: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundContentNeutralSecondary: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundContentBrandPrimary: '{foregroundCtrlBrandRest}',
};

export const lightColors: ThemeColors = {
  ...lightNullColors,
  ...lightBackgroundColors,
  ...lightStrokeColors,
  ...lightForegroundColors,
};
