import {
  alphaBlack,
  alphaWhite,
  neutral,
  shadow,
  statusDanger,
  statusSuccess,
  statusWarning,
  vibrant,
} from './globalColors.js';

import type {
  ThemeBackgroundColors,
  ThemeForegroundColors,
  ThemeMaterialColors,
  ThemeNullColors,
  ThemeShadowColors,
  ThemeStatusColors,
  ThemeStrokeColors,
} from './themeColors.js';

export const lightNullColors: ThemeNullColors = {
  nullColor: alphaWhite[0],
  nullColorBackground: '{nullColor}',
};

export const lightBackgroundColors: ThemeBackgroundColors = {
  backgroundCtrlBrandRest: neutral[750],
  backgroundCtrlBrandHover: neutral[754],
  backgroundCtrlBrandPressed: neutral[758],
  backgroundCtrlBrandDisabled: neutral[200],
  backgroundCtrlActivebrandRest: '{backgroundCtrlBrandRest}',
  backgroundCtrlActivebrandHover: '{backgroundCtrlBrandHover}',
  backgroundCtrlActivebrandPressed: '{backgroundCtrlBrandPressed}',
  backgroundCtrlActivebrandDisabled: '{backgroundCtrlBrandDisabled}',
  backgroundCtrlNeutralRest: neutral[150],
  backgroundCtrlNeutralHover: neutral[154],
  backgroundCtrlNeutralPressed: neutral[158],
  backgroundCtrlNeutralDisabled: neutral[200],
  backgroundCtrlSubtleRest: alphaWhite[0],
  backgroundCtrlSubtleHover: neutral[4],
  backgroundCtrlSubtlePressed: neutral[8],
  backgroundCtrlSubtleDisabled: alphaWhite[0],
  backgroundCtrlSubtleHoverSplit: '{nullColor}',
  backgroundCtrlOutlineRest: '{nullColor}',
  backgroundCtrlOutlineHover: '{nullColor}',
  backgroundCtrlOutlinePressed: '{nullColor}',
  backgroundCtrlOutlineDisabled: '{nullColor}',
  backgroundCtrlOnImageRest: alphaBlack[60],
  backgroundCtrlOnImageHover: alphaBlack[50],
  backgroundCtrlOnImagePressed: alphaBlack[40],
  backgroundCtrlShapesafeNeutralRest: neutral[400],
  backgroundCtrlShapesafeNeutralHover: '{backgroundCtrlShapesafeNeutralRest}',
  backgroundCtrlShapesafeNeutralPressed: '{backgroundCtrlShapesafeNeutralRest}',
  backgroundCtrlShapesafeNeutralDisabled:
    '{foregroundCtrlNeutralPrimaryDisabled}',
  backgroundCtrlShapesafeActivebrandRest: '{foregroundCtrlBrandRest}',
  backgroundCtrlShapesafeActivebrandDisabled: '{foregroundCtrlBrandDisabled}',
  backgroundControlProgressBarEmptyRest: '{ctrlProgressBackgroundEmpty}',
  backgroundCardOnPrimaryDefaultRest: neutral[0],
  backgroundCardOnPrimaryDefaultHover: neutral[4],
  backgroundCardOnPrimaryDefaultPressed: neutral[8],
  backgroundCardOnPrimaryDefaultDisabled: neutral[200],
  backgroundCardOnPrimaryDefaultSelected: neutral[150],
  backgroundCardOnPrimaryAltRest: vibrant[100],
  backgroundCardOnPrimaryAltHover: vibrant[200],
  backgroundCardOnPrimaryAltPressed: vibrant[300],
  backgroundCardOnPrimaryAltDisabled: neutral[200],
  backgroundCardOnSecondaryDefaultRest: neutral[0],
  backgroundCardOnSecondaryDefaultHover: neutral[0],
  backgroundCardOnSecondaryDefaultPressed: neutral[0],
  backgroundCardOnSecondaryDefaultDisabled: neutral[0],
  backgroundCardOnSecondaryAltRest: neutral[0],
  backgroundCardOnSecondaryAltHover: neutral[0],
  backgroundCardOnSecondaryAltPressed: neutral[0],
  backgroundCardOnSecondaryAltDisabled: neutral[0],
  backgroundCardOnFlyoutDefaultRest: neutral[0],
  backgroundCardOnFlyoutDefaultHover: neutral[0],
  backgroundCardOnFlyoutDefaultPressed: neutral[0],
  backgroundCardOnFlyoutDefaultDisabled: neutral[0],
  backgroundWebPagePrimary: neutral[0],
  backgroundWebPageSecondary: neutral[0],
  backgroundFlyoutSolid: neutral[0],
  backgroundFlyoutLumBlend: neutral[0],
  backgroundFlyoutColorBlend: neutral[0],
  backgroundToolbar: '{backgroundCardOnPrimaryDefaultRest}',
  backgroundLayerPrimarySolid: neutral[0],
  backgroundLayerPrimaryStop1: neutral[0],
  backgroundLayerPrimaryStop2: neutral[0],
  backgroundLayerPrimaryStop3: neutral[0],
  backgroundLayerSecondary: neutral[100],
  backgroundLayerTertiary: neutral[100],
  backgroundWindowTabBandSolid: neutral[250],
  backgroundWindowTabBandInactive: neutral[200],
  backgroundWindowTabBandLumBlend: neutral[0],
  backgroundWindowTabBandColorBlend: neutral[0],
  backgroundWindowPrimarySolid: neutral[0],
  backgroundWindowPrimaryLumBlend: neutral[0],
  backgroundWindowPrimaryColorBlend: neutral[0],
  backgroundWindowSecondarySolid: neutral[0],
  backgroundWindowSecondaryLumBlend: neutral[0],
  backgroundWindowSecondaryColorBlend: neutral[0],
  backgroundSmoke: alphaBlack[30],
};

export const lightStrokeColors: ThemeStrokeColors = {
  strokeCardOnprimaryDisabled: '{nullColor}',
  strokeCardOnprimaryHover: '{nullColor}',
  strokeCardOnprimaryPressed: '{nullColor}',
  strokeCardOnprimaryRest: '{nullColor}',
  strokeCardOnSecondaryDisabled: '{nullColor}',
  strokeCardOnSecondaryHover: '{nullColor}',
  strokeCardOnSecondaryPressed: '{nullColor}',
  strokeCardOnSecondaryRest: '{nullColor}',
  strokeCardSelected: '{nullColor}',
  strokeCtrlDividerOnActivebrand: '{strokeCtrlDividerOnBrand}',
  strokeCtrlDividerOnActivebrandDisabled: '{strokeCtrlDividerOnBrandDisabled}',
  strokeCtrlDividerOnBrand: alphaWhite[0],
  strokeCtrlDividerOnBrandDisabled: '{nullColor}',
  strokeCtrlDividerOnneutral: alphaWhite[0],
  strokeCtrlDividerOnneutralDisabled: '{nullColor}',
  strokeCtrlDividerOnOutline: alphaWhite[0],
  strokeCtrlDividerOnOutlineDisabled: '{nullColor}',
  strokeCtrlDividerOnSubtle: '{nullColor}',
  strokeCtrlDividerOnSubtleDisabled: '{nullColor}',
  strokeCtrlOnactivebrandDisabled: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnactivebrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnactivebrandHover: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnactivebrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnactivebrandPressed: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnactivebrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnactivebrandRest: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnactivebrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnBrandDisabled: '{nullColor}',
  strokeCtrlOnBrandDisabledStop2: '{strokeCtrlOnBrandDisabled}',
  strokeCtrlOnBrandHover: '{nullColor}',
  strokeCtrlOnBrandHoverStop2: '{strokeCtrlOnBrandHover}',
  strokeCtrlOnBrandPressed: '{nullColor}',
  strokeCtrlOnBrandPressedStop2: '{strokeCtrlOnBrandPressed}',
  strokeCtrlOnBrandRest: '{nullColor}',
  strokeCtrlOnBrandRestStop2: '{strokeCtrlOnBrandRest}',
  strokeCtrlOnneutralDisabled: '{nullColor}',
  strokeCtrlOnneutralDisabledStop2: '{strokeCtrlOnneutralDisabled}',
  strokeCtrlOnneutralHover: '{nullColor}',
  strokeCtrlOnneutralHoverStop2: '{strokeCtrlOnneutralHover}',
  strokeCtrlOnneutralPressed: '{nullColor}',
  strokeCtrlOnneutralPressedStop2: '{strokeCtrlOnneutralPressed}',
  strokeCtrlOnneutralRest: '{nullColor}',
  strokeCtrlOnneutralRestStop2: '{strokeCtrlOnneutralRest}',
  strokeCtrlOnoutlineDisabled: neutral[200],
  strokeCtrlOnoutlineDisabledStop2: '{strokeCtrlOnOutlineDisabled}',
  strokeCtrlOnoutlineHover: neutral[304],
  strokeCtrlOnoutlineHoverStop2: '{strokeCtrlOnOutlineHover}',
  strokeCtrlOnoutlinePressed: neutral[308],
  strokeCtrlOnoutlinePressedStop2: '{strokeCtrlOnOutlinePressed}',
  strokeCtrlOnoutlineRest: neutral[300],
  strokeCtrlOnoutlineRestStop2: '{strokeCtrlOnOutlineRest}',
  strokeCtrlOnsubtleDisabled: '{nullColor}',
  strokeCtrlOnsubtleHover: '{nullColor}',
  strokeCtrlOnsubtleHoverSplit: '{nullColor}',
  strokeCtrlOnsubtlePressed: '{nullColor}',
  strokeCtrlOnsubtleRest: '{nullColor}',
  strokeDividerBrand: '{backgroundCtrlBrandRest}',
  strokeDividerDefault: neutral[300],
  strokeDividerStrong: '{strokeDividerDefault}',
  strokeDividerSubtle: neutral[200],
  strokeFlyout: '{nullColor}',
  strokeImage: '{nullColor}',
  strokeLayer: '{nullColor}',
  strokeToolbar: '{nullColor}',
  strokeWindowActive: alphaWhite[0],
  strokeWindowInactive: '{strokeWindowActive}',
};

export const lightForegroundColors: ThemeForegroundColors = {
  foregroundCtrlNeutralPrimaryRest: neutral[800],
  foregroundCtrlNeutralPrimaryHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlNeutralPrimaryDisabled: neutral[350],
  foregroundCtrlNeutralSecondaryRest: neutral[450],
  foregroundCtrlNeutralSecondaryHover: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryPressed: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundCtrlNeutralSecondaryDisabled: neutral[350],
  foregroundCtrlOnOutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnOutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOnSubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOnSubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlOntransparentRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOntransparentHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOntransparentPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlOntransparentDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnneutralRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnneutralHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnneutralPressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnneutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnOutlineRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlineHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlinePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnOutlineDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlIconOnSubtleRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtleHover: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtlePressed: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundCtrlIconOnSubtleDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  foregroundCtrlBrandRest: neutral[750],
  foregroundCtrlBrandHover: neutral[750],
  foregroundCtrlBrandPressed: neutral[750],
  foregroundCtrlBrandDisabled: neutral[350],
  foregroundCtrlActivebrandRest: '{foregroundCtrlBrandRest}',
  foregroundCtrlActivebrandHover: '{foregroundCtrlBrandHover}',
  foregroundCtrlActivebrandPressed: '{foregroundCtrlBrandPressed}',
  foregroundCtrlActivebrandDisabled: '{foregroundCtrlBrandDisabled}',
  foregroundCtrlOnBrandRest: neutral[0],
  foregroundCtrlOnBrandHover: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnBrandPressed: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnBrandDisabled: neutral[350],
  foregroundCtrlOnActivebrandRest: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActivebrandHover: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActivebrandPressed: '{foregroundCtrlOnBrandRest}',
  foregroundCtrlOnActivebrandDisabled: '{foregroundCtrlOnBrandDisabled}',
  foregroundCtrlHintDefault: neutral[300],
  foregroundCtrlOnImageRest: neutral[0],
  foregroundControlShapeSafeNeutralRest: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundControlShapeSafeNeutralHover: '{foregroundCtrlNeutralPrimaryHover}',
  foregroundControlShapeSafeNeutralPressed:
    '{foregroundCtrlNeutralPrimaryPressed}',
  foregroundControlOnBrandRest: '{foregroundCtrlOnBrandRest}',
  foregroundControlLinkBrandRest: '{ctrlLinkForegroundBrandRest}',
  foregroundContentNeutralPrimary: '{foregroundCtrlNeutralPrimaryRest}',
  foregroundContentNeutralSecondary: '{foregroundCtrlNeutralSecondaryRest}',
  foregroundContentBrandPrimary: '{foregroundCtrlBrandRest}',
  foregroundNeutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
};

export const lightShadowColors: ThemeShadowColors = {
  shadowToolbarKeyColor: shadow.shadowKeyLowLight,
  shadowToolbarAmbientColor: shadow.shadowAmbientLowLight,
  shadowWindowActiveKeyColor: shadow.shadowKeyHighLight,
  shadowWindowActiveAmbientColor: shadow.shadowAmbientHighLight,
  shadowWindowInactiveKeyColor: shadow.shadowKeyHighLight,
  shadowWindowInactiveAmbientColor: shadow.shadowAmbientHighLight,
  shadowCardRestKeyColor: '{nullColor}',
  shadowCardRestAmbientColor: '{nullColor}',
  shadowCardHoverKeyColor: '{nullColor}',
  shadowCardPressedKeyColor: '{nullColor}',
  shadowCardDisabledKeyColor: '{nullColor}',
  shadowFlyoutKeyColor: shadow.shadowKeyLowLight,
  shadowFlyoutAmbientColor: shadow.shadowAmbientLowLight,
  shadowCtrlOnDragKeyColor: '{shadowFlyoutKeyColor}',
  shadowCtrlOnDragAmbientColor: '{shadowFlyoutAmbientColor}',
  shadowLayerKeyColor: shadow.shadowKeyHighLight,
  shadowLayerAmbientColor: shadow.shadowAmbientHighLight,
};

export const lightMaterialColors: ThemeMaterialColors = {
  materialAcrylicDefaultSolid: neutral[0],
  materialAcrylicDefaultColorBlend: '{nullColor}',
  materialAcrylicDefaultLumBlend: '{nullColor}',
  materialAcrylicShellDefaultSolid: neutral[0],
  materialAcrylicShellDefaultColorBlend: neutral[0],
  materialAcrylicShellDefaultLumBlend: neutral[0],
  materialMicaThinSolid: neutral[0],
  materialMicaThinColorBlend: neutral[0],
  materialMicaThinLumBlend: neutral[0],
  materialMicaDarkerSolid: neutral[0],
  materialMicaDarkerColorBlend: neutral[0],
  materialMicaDarkerLumBlend: neutral[0],
  materialMicaDefaultSolid: neutral[0],
  materialMicaDefaultColorBlend: neutral[0],
  materialMicaDefaultLumBlend: neutral[0],
};

export const lightStatusColors: ThemeStatusColors = {
  statusBrandBackground: vibrant[600],
  statusBrandForeground: neutral[0],
  statusBrandStroke: vibrant[500],
  statusBrandTintBackground: vibrant[100],
  statusBrandTintForeground: vibrant[600],
  statusBrandTintStroke: alphaWhite[0],
  statusDangerBackground: statusDanger[600],
  statusDangerForeground: neutral[0],
  statusDangerStroke: statusDanger[500],
  statusDangerTintBackground: statusDanger[100],
  statusDangerTintForeground: statusDanger[600],
  statusDangerTintStroke: alphaWhite[0],
  statusSuccessBackground: statusSuccess[600],
  statusSuccessForeground: neutral[0],
  statusSuccessStroke: statusSuccess[500],
  statusSuccessTintBackground: statusSuccess[100],
  statusSuccessTintForeground: statusSuccess[600],
  statusSuccessTintStroke: alphaWhite[0],
  statusWarningBackground: statusWarning[600],
  statusWarningForeground: neutral[0],
  statusWarningStroke: statusWarning[500],
  statusWarningTintBackground: statusWarning[100],
  statusWarningTintForeground: statusWarning[600],
  statusWarningTintStroke: alphaWhite[0],
  statusInformativeBackground: vibrant[100],
  statusInformativeForeground: neutral[500],
  statusInformativeStroke: '{nullColor}',
  statusInformativeTintBackground: neutral[150],
  statusInformativeTintForeground: neutral[800],
  statusInformativeTintStroke: alphaWhite[0],
  statusImportantBackground: '{nullColor}',
  statusImportantForeground: '{nullColor}',
  statusImportantStroke: alphaWhite[0],
  statusImportantTintBackground: alphaWhite[0],
  statusImportantTintForeground: alphaWhite[0],
  statusImportantTintStroke: alphaWhite[0],
  statusAwayForeground: '#c85d00', // Kumo vibrant.orange.600
  statusOofForeground: '#8a42ab', // Kumo vibrant.purple.600
};
