import { alphaBlack, alphaWhite, neutral, vibrant } from './globalColors.js';

export const lightNullColors: ThemeNullColors = {
  nullColor: 'rgba(255, 255, 255, 0)',
};

export const lightBackgroundColors: ThemeBackgroundColors = {
  backgroundCtrlBrandRest: neutral[750],
  backgroundCtrlBrandHover: neutral[754],
  backgroundCtrlBrandPressed: neutral[758],
  backgroundCtrlBrandDisabled: neutral[200],
  backgroundActiveBrandRest: neutral[750],
  backgroundActiveBrandHover: neutral[754],
  backgroundActiveBrandPressed: neutral[758],
  backgroundActiveBrandDisabled: neutral[200],
  backgroundNeutralRest: neutral[150],
  backgroundNeutralHover: neutral[154],
  backgroundNeutralPressed: neutral[158],
  backgroundNeutralDisabled: neutral[200],
  backgroundSubtleRest: alphaWhite[0],
  backgroundSubtleHover: neutral[4],
  backgroundSubtlePressed: neutral[8],
  backgroundSubtleDisabled: alphaWhite[0],
  backgroundSubtleHoverSplit: lightNullColors.nullColor,
  backgroundOutlineRest: lightNullColors.nullColor,
  backgroundOutlineHover: lightNullColors.nullColor,
  backgroundOutlinePressed: lightNullColors.nullColor,
  backgroundOutlineDisabled: lightNullColors.nullColor,
  backgroundOnImageRest: alphaBlack[60],
  backgroundOnImageHover: alphaBlack[50],
  backgroundOnImagePressed: alphaBlack[40],
  backgroundShapeSafeNeutralRest: neutral[400],
  backgroundShapeSafeNeutralHover: '{backgroundShapeSafeNeutralRest}',
  backgroundShapeSafeNeutralPressed: '{backgroundShapeSafeNeutralRest}',
  backgroundShapeSafeNeutralDisabled: '{foregroundCtrlNeutralPrimaryDisabled}',
  backgroundShapeSafeActiveBrandRest: '{foregroundCtrlBrandRest}',
  backgroundShapeSafeActiveBrandDisabled: '{foregroundCtrlBrandDisabled}',
  backgroundCardOnPrimaryDefaultRest: neutral[0],
  backgroundCardOnPrimaryDefaultHover: neutral[4],
  backgroundCardOnPrimaryDefaultPressed: neutral[8],
  backgroundCardOnPrimaryDefaultDisabled: neutral[200],
  backgroundCardOnPrimaryDefaultSelected: neutral[150],
  backgroundCardOnPrimaryAltRest: vibrant[100],
  backgroundCardOnPrimaryAltHover: vibrant[200],
  backgroundCardOnPrimaryAltPressed: vibrant[300],
  backgroundCardOnPrimaryAltDisabled: neutral[200],
  backgroundCardOnSecondaryDefaultRest: neutral[0],
  backgroundCardOnSecondaryDefaultHover: neutral[0],
  backgroundCardOnSecondaryDefaultPressed: neutral[0],
  backgroundCardOnSecondaryDefaultDisabled: neutral[0],
  backgroundCardOnSecondaryAltRest: neutral[0],
  backgroundCardOnSecondaryAltHover: neutral[0],
  backgroundCardOnSecondaryAltPressed: neutral[0],
  backgroundCardOnSecondaryAltDisabled: neutral[0],
  backgroundCardOnFlyoutDefaultRest: neutral[0],
  backgroundCardOnFlyoutDefaultHover: neutral[0],
  backgroundCardOnFlyoutDefaultPressed: neutral[0],
  backgroundCardOnFlyoutDefaultDisabled: neutral[0],
  backgroundWebPagePrimary: neutral[0],
  backgroundWebPageSecondary: neutral[0],
  backgroundFlyoutSolid: neutral[0],
  backgroundFlyoutLumBlend: neutral[0],
  backgroundFlyoutColorBlend: neutral[0],
  backgroundToolbar: '{backgroundCardOnPrimaryDefaultRest}',
  backgroundLayerPrimarySolid: '',
  backgroundLayerPrimaryStop1: '',
  backgroundLayerPrimaryStop2: '',
  backgroundLayerPrimaryStop3: '',
  backgroundLayerSecondary: '',
  backgroundLayerTertiary: '',
  backgroundWindowTabBandSolid: '',
  backgroundWindowTabBandInactive: '',
  backgroundWindowLumBlend: '',
  backgroundWindowColorBlend: '',
  backgroundWindowPrimarySolid: '',
  backgroundWindowPrimaryLumBlend: '',
  backgroundWindowPrimaryColorBlend: '',
  backgroundWindowSecondarySolid: '',
  backgroundWindowSecondaryLumBlend: '',
  backgroundWindowSecondaryColorBlend: '',
  backgroundSmoke: '',
};

export const lightColors: ThemeColors = {
  ...lightNullColors,
  ...lightBackgroundColors,
};
