import {
  lightBackgroundColors,
  lightForegroundColors,
  lightMaterialColors,
  lightNullColors,
  lightShadowColors,
  lightStatusColors,
  lightStrokeColors,
} from './lightThemeColors.js';
import {
  lightAvatarColors,
  lightChoiceColors,
  lightComposerColors,
  lightDialogColors,
  lightDragColors,
  lightIdentityFlyoutColors,
  lightInputColors,
  lightFabColors,
  lightFocusColors,
  lightLinkColors,
  lightListColors,
  lightLiteFilterColors,
  lightOmniboxColors,
  lightProgressColors,
  lightRatingColors,
  lightSegmentedColors,
  lightSliderColors,
  lightTabColors,
  lightTooltipColors,
} from './lightCtrlColors.js';
import {
  darkBackgroundColors,
  darkForegroundColors,
  darkMaterialColors,
  darkNullColors,
  darkShadowColors,
  darkStatusColors,
  darkStrokeColors,
} from './darkThemeColors.js';
import {
  darkAvatarColors,
  darkChoiceColors,
  darkComposerColors,
  darkDialogColors,
  darkDragColors,
  darkIdentityFlyoutColors,
  darkInputColors,
  darkFabColors,
  darkFocusColors,
  darkLinkColors,
  darkListColors,
  darkLiteFilterColors,
  darkOmniboxColors,
  darkProgressColors,
  darkRatingColors,
  darkSegmentedColors,
  darkSliderColors,
  darkTabColors,
  darkTooltipColors,
} from './darkCtrlColors.js';
import { iconTheme } from './iconTheme.js';
import { material } from './material.js';
import {
  paddingCard,
  paddingCtrl,
  paddingCtrlSm,
  paddingCtrlLg,
  paddingContent,
  paddingFlyout,
  paddingToolbar,
} from './padding.js';
import { shadow, shadowParts } from './shadow.js';
import { sizeCtrl, sizeCtrlLg, sizeCtrlSm } from './size.js';
import { strokeWidth } from './strokeWidth.js';
import {
  textCtrl,
  textGlobal,
  textRamp,
  textRampLg,
  textRampSm,
  textStyle,
} from './text.js';

export const utilityLayout = {
  ...iconTheme,
  ...material,
  ...paddingCard,
  ...paddingCtrl,
  ...paddingCtrlSm,
  ...paddingCtrlLg,
  ...paddingContent,
  ...paddingFlyout,
  ...paddingToolbar,
  ...shadow,
  ...shadowParts,
  ...sizeCtrl,
  ...sizeCtrlLg,
  ...sizeCtrlSm,
  ...strokeWidth,
  ...textCtrl,
  ...textGlobal,
  ...textRamp,
  ...textRampLg,
  ...textRampSm,
  ...textStyle,
};

export const lightTheme = {
  ...utilityLayout,
  ...lightBackgroundColors,
  ...lightForegroundColors,
  ...lightMaterialColors,
  ...lightNullColors,
  ...lightShadowColors,
  ...lightStatusColors,
  ...lightStrokeColors,
  ...lightAvatarColors,
  ...lightChoiceColors,
  ...lightComposerColors,
  ...lightDialogColors,
  ...lightDragColors,
  ...lightIdentityFlyoutColors,
  ...lightInputColors,
  ...lightFabColors,
  ...lightFocusColors,
  ...lightLinkColors,
  ...lightListColors,
  ...lightLiteFilterColors,
  ...lightOmniboxColors,
  ...lightProgressColors,
  ...lightRatingColors,
  ...lightSegmentedColors,
  ...lightSliderColors,
  ...lightTabColors,
  ...lightTooltipColors,
};

export const darkTheme = {
  ...utilityLayout,
  ...darkBackgroundColors,
  ...darkForegroundColors,
  ...darkMaterialColors,
  ...darkNullColors,
  ...darkShadowColors,
  ...darkStatusColors,
  ...darkStrokeColors,
  ...darkAvatarColors,
  ...darkChoiceColors,
  ...darkComposerColors,
  ...darkDialogColors,
  ...darkDragColors,
  ...darkIdentityFlyoutColors,
  ...darkInputColors,
  ...darkFabColors,
  ...darkFocusColors,
  ...darkLinkColors,
  ...darkListColors,
  ...darkLiteFilterColors,
  ...darkOmniboxColors,
  ...darkProgressColors,
  ...darkRatingColors,
  ...darkSegmentedColors,
  ...darkSliderColors,
  ...darkTabColors,
  ...darkTooltipColors,
};

export type Theme = typeof lightTheme | typeof darkTheme;
export type Layout = typeof utilityLayout;