import {
  lightBackgroundColors,
  lightForegroundColors,
  lightMaterialColors,
  lightNullColors,
  lightShadowColors,
  lightStatusColors,
  lightStrokeColors,
} from './lightThemeColors.js';
import {
  lightAvatarColors,
  lightChoiceColors,
  lightComposerColors,
  lightDialogColors,
  lightDragColors,
  lightIdentityFlyoutColors,
  lightInputColors,
  lightFabColors,
  lightFocusColors,
  lightLinkColors,
  lightListColors,
  lightLiteFilterColors,
  lightOmniboxColors,
  lightProgressColors,
  lightRatingColors,
  lightSegmentedColors,
  lightSliderColors,
  lightTabColors,
  lightTooltipColors,
} from './lightCtrlColors.js';
import {
  darkBackgroundColors,
  darkForegroundColors,
  darkMaterialColors,
  darkNullColors,
  darkShadowColors,
  darkStatusColors,
  darkStrokeColors,
} from './darkThemeColors.js';
import {
  darkAvatarColors,
  darkChoiceColors,
  darkComposerColors,
  darkDialogColors,
  darkDragColors,
  darkIdentityFlyoutColors,
  darkInputColors,
  darkFabColors,
  darkFocusColors,
  darkLinkColors,
  darkListColors,
  darkLiteFilterColors,
  darkOmniboxColors,
  darkProgressColors,
  darkRatingColors,
  darkSegmentedColors,
  darkSliderColors,
  darkTabColors,
  darkTooltipColors,
} from './darkCtrlColors.js';
import { corner } from './corner.js';
import {
  ctrlAvatarLayout,
  ctrlChoiceLayout,
  ctrlBadgeLayout,
  ctrlBooleanLayout,
  ctrlComposerLayout,
  ctrlDialogLayout,
  ctrlDividerLayout,
  ctrlFabLayout,
  ctrlFocusLayout,
  ctrlInputLayout,
  ctrlLinkLayout,
  ctrlListLayout,
  ctrlLiteFilterLayout,
  ctrlProgressLayout,
  ctrlRatingLayout,
  ctrlSegmentedLayout,
  ctrlSliderLayout,
  ctrlSpinnerLayout,
  ctrlSplitLayout,
  ctrlTooltipLayout,
} from './ctrlLayout.js';
import { iconTheme } from './iconTheme.js';
import { material } from './material.js';
import {
  paddingCard,
  paddingCtrl,
  paddingCtrlSm,
  paddingCtrlLg,
  paddingContent,
  paddingFlyout,
  paddingToolbar,
} from './padding.js';
import { gapBetween, gapInside } from './gap.js';
import { shadow, shadowParts } from './shadow.js';
import { sizeCtrl, sizeCtrlLg, sizeCtrlSm } from './size.js';
import { strokeWidth } from './strokeWidth.js';
import {
  textCtrl,
  textGlobal,
  textRamp,
  textRampLg,
  textRampSm,
  textStyle,
} from './text.js';
import { nullValues } from './nullValues.js';
import {
  legacyCommonTokens,
  legacyDarkTokens,
  legacyLightTokens,
} from './legacyTokens.js';

import { resolveNestedVariables } from './resolveNestedVariables.js';

const utilityLayoutTemplate = {
  ...corner,
  ...ctrlAvatarLayout,
  ...ctrlBadgeLayout,
  ...ctrlBooleanLayout,
  ...ctrlChoiceLayout,
  ...ctrlComposerLayout,
  ...ctrlDialogLayout,
  ...ctrlDividerLayout,
  ...ctrlFabLayout,
  ...ctrlFocusLayout,
  ...ctrlInputLayout,
  ...ctrlLinkLayout,
  ...ctrlListLayout,
  ...ctrlLiteFilterLayout,
  ...ctrlProgressLayout,
  ...ctrlRatingLayout,
  ...ctrlSegmentedLayout,
  ...ctrlSliderLayout,
  ...ctrlSpinnerLayout,
  ...ctrlSplitLayout,
  ...ctrlTooltipLayout,
  ...gapBetween,
  ...gapInside,
  ...iconTheme,
  ...legacyCommonTokens,
  ...material,
  ...nullValues,
  ...paddingCard,
  ...paddingContent,
  ...paddingCtrl,
  ...paddingCtrlLg,
  ...paddingCtrlSm,
  ...paddingFlyout,
  ...paddingToolbar,
  ...shadow,
  ...shadowParts,
  ...sizeCtrl,
  ...sizeCtrlLg,
  ...sizeCtrlSm,
  ...strokeWidth,
  ...textCtrl,
  ...textGlobal,
  ...textRamp,
  ...textRampLg,
  ...textRampSm,
  ...textStyle,
};

export const lightTheme = resolveNestedVariables({
  ...legacyLightTokens,
  ...lightAvatarColors,
  ...lightBackgroundColors,
  ...lightChoiceColors,
  ...lightComposerColors,
  ...lightDialogColors,
  ...lightDragColors,
  ...lightFabColors,
  ...lightFocusColors,
  ...lightForegroundColors,
  ...lightIdentityFlyoutColors,
  ...lightInputColors,
  ...lightLinkColors,
  ...lightListColors,
  ...lightLiteFilterColors,
  ...lightMaterialColors,
  ...lightNullColors,
  ...lightOmniboxColors,
  ...lightProgressColors,
  ...lightRatingColors,
  ...lightSegmentedColors,
  ...lightShadowColors,
  ...lightSliderColors,
  ...lightStatusColors,
  ...lightStrokeColors,
  ...lightTabColors,
  ...lightTooltipColors,
  ...utilityLayoutTemplate,
});

export const darkTheme = resolveNestedVariables({
  ...darkAvatarColors,
  ...darkBackgroundColors,
  ...darkChoiceColors,
  ...darkComposerColors,
  ...darkDialogColors,
  ...darkDragColors,
  ...darkFabColors,
  ...darkFocusColors,
  ...darkForegroundColors,
  ...darkIdentityFlyoutColors,
  ...darkInputColors,
  ...darkLinkColors,
  ...darkListColors,
  ...darkLiteFilterColors,
  ...darkMaterialColors,
  ...darkNullColors,
  ...darkOmniboxColors,
  ...darkProgressColors,
  ...darkRatingColors,
  ...darkSegmentedColors,
  ...darkShadowColors,
  ...darkSliderColors,
  ...darkStatusColors,
  ...darkStrokeColors,
  ...darkTabColors,
  ...darkTooltipColors,
  ...legacyDarkTokens,
  ...utilityLayoutTemplate,
});

export type Theme = typeof lightTheme;
