/* eslint-disable no-undef */
import esbuild from 'esbuild';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import {
  phoenixLightThemeSolidWin11,
  phoenixDarkThemeSolidWin11,
} from '@phoenixui/themes';
import fs from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));

function phxCssVarsToTokens(cssVars) {
  let tokenString = 'export const kumoToPhoenix = {\n';
  let unmappped = '';
  for (const [key, value] of Object.entries(cssVars)) {
    if (value.startsWith('var(--')) {
      const tokenName = value.slice(6).substring(0, value.length - 7);
      tokenString += `  ${key}: '${tokenName}',\n`;
    } else {
      unmappped += `  ${key}: '${value}',\n`;
    }
  }
  return (tokenString += `  // Unmappable tokens\n${unmappped}};\n`);
}

function phxCssVarsToValues(cssVars, theme = 'light') {
  let themeString = `export const ${theme}Theme = {\n`;
  let unmappped = '';
  for (const [key, value] of Object.entries(cssVars)) {
    if (value.startsWith('var(--')) {
      const tokenName = value.slice(6).substring(0, value.length - 7);
      const phxValue =
        theme === 'light'
          ? phoenixLightThemeSolidWin11[tokenName]
          : phoenixDarkThemeSolidWin11[tokenName];
      themeString += `  ${key}: '${phxValue}',\n`;
    } else {
      unmappped += `  ${key}: '${value}',\n`;
    }
  }
  return (themeString += `  // Unmappable tokens\n${unmappped}};\n`);
}

esbuild
  .build({
    entryPoints: {
      index: join(__dirname, '../src/index.ts'),
    },
    bundle: true,
    format: 'esm',
    target: 'esnext',
    sourcemap: 'external',
    outdir: join(__dirname, '../dist/esm'),
  })
  .then(async () => {
    const kumoThemes = await import('../dist/esm/index.js');

    // Write individual tokens to file
    fs.writeFileSync(
      join(__dirname, '../dist/esm/tokens.js'),
      '// Auto generated by scripts/build.js\n' +
        Object.entries(kumoThemes.tokens)
          .map(([key, value]) => `export const ${key} = '${value}';\n`)
          .join(''),
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/tokens.d.ts'),
      '// Auto generated by scripts/build.js\n' +
        Object.keys(kumoThemes.tokens)
          .map((key) => `export declare const ${key}: string;\n`)
          .join(''),
    );

    const kumoLightTheme = kumoThemes.lightTheme();

    // Write ressolved themes to file
    fs.writeFileSync(
      join(__dirname, '../dist/esm/lightTheme.js'),
      '// Auto generated by scripts/build.js\n' +
        phxCssVarsToValues(kumoLightTheme, 'light'),
      { encoding: 'utf-8' },
    );
    fs.writeFileSync(
      join(__dirname, '../dist/esm/darkTheme.js'),
      '// Auto generated by scripts/build.js\n' +
        phxCssVarsToValues(kumoThemes.darkTheme(), 'dark'),
      { encoding: 'utf-8' },
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/lightTheme.d.ts'),
      '// Auto generated by scripts/build.js\nimport type { Theme } from "./themes.d.ts";\nexport declare const lightTheme: Theme;\n',
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/darkTheme.d.ts'),
      '// Auto generated by scripts/build.js\nimport type { Theme } from "./themes.d.ts";\nexport declare const darkTheme: Theme;\n',
    );

    // Write kumo -> phoenix mappings to file
    fs.writeFileSync(
      join(__dirname, '../dist/esm/kumoToPhoenix.js'),
      '// Auto generated by scripts/build.js\n' +
        phxCssVarsToTokens(kumoLightTheme),
      { encoding: 'utf-8' },
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/kumoToPhoenix.d.ts'),
      '// Auto generated by scripts/build.js\nexport declare const kumoToPhoenix: Record<string, string>;\n',
    );

    // TODO: Write phoenix -> kumo mappings to file
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
