/**
 * This script generates an index file for each component with variables that can be used
 * in css tag template literals (or any other .ts or .js file).
 */

/* global console */

import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.resolve(path.dirname(__filename), '../');

function getCSSVar(name, fallback, prefix) {
  return `var(--${prefix ? `${prefix}-` : ''}${name}${fallback ? `, ${fallback}` : ''})`;
}

function getExportConst(dependency) {
  const startCSSString = `export const ${dependency.name} = "`;
  const endCSSString = `";\n`;
  let commentString = '';

  if (dependency.$comment) {
    commentString = `// ${dependency.$comment}\n`;
  }

  if (dependency.smtc) {
    if (dependency.ctrl) {
      return `${commentString}${startCSSString}${getCSSVar(dependency.smtc, getCSSVar(dependency.smtc, getCSSVar(dependency.f2), 'smtc'), 'ctrl')}${endCSSString}`;
    } else {
      return `${commentString}${startCSSString}${getCSSVar(dependency.smtc, getCSSVar(dependency.f2), 'smtc')}${endCSSString}`;
    }
  } else {
    return `${commentString}${startCSSString}${getCSSVar(dependency.f2)}${endCSSString}`;
  }
}

function getExportCSS(dependency) {
  const startCSSString = `export const ${dependency.name}Css = "`;
  const endCSSString = `";\n`;

  return `${startCSSString}--smtc-${dependency.smtc}: ${dependency.smtc_css}${endCSSString}`;
}

function buildFile(component) {
  const data = fs.readFileSync(
    path.resolve(__dirname, 'src', `${component}.json`),
    'utf-8',
  );
  const dependencies = JSON.parse(data);
  if (dependencies) {
    let content = '';
    const names = [];

    dependencies.forEach((dependency) => {
      if (dependency.extends) {
        content += buildFile(dependency.extends);
        return;
      }

      let name = dependency.name;

      if (names.includes(name)) {
        const err = new Error(`The name ${name} has already been used.`);
        console.error(err);
        throw err;
      }

      content += getExportConst(dependency);

      if (dependency.smtc_css) {
        content += getExportCSS(dependency);
      }

      names.push(name);
    });

    return content;
  } else {
    console.error(`No dependencies found for ${component}.json. Skipping...`);
  }
}

function writeFile(fileName, content) {
  content = '// File contents generated by scripts/generate.js\n' + content;
  fs.writeFileSync(path.resolve(__dirname, 'src', `${fileName}.ts`), content, {
    type: 'utf-8',
  });
}

// Get the list of component JSON files in src
const components = fs
  .readdirSync(path.resolve(__dirname, 'src'), {
    withFileTypes: true,
  })
  .filter((entry) => entry.isFile() && entry.name.endsWith('.json'))
  .map((file) => file.name.replace('.json', ''));

// Write out each component file
let mainFileContent = '';
components.forEach((component) => {
  console.log(`Building ${component}...`);
  const fileContent = buildFile(component);
  mainFileContent += fileContent;
  writeFile(component, fileContent);
});

// Dedupe main file content
mainFileContent = mainFileContent
  .split('\n')
  .filter((line, index, self) => self.indexOf(line) === index)
  .join('\n');

// Export all tokens as a single object
let tokenObject = '\nexport const tokens = {\n';
mainFileContent.split('\n').forEach((token) => {
  const tokenName = token.split(' = ')[0].replace('export const ', '');
  if (tokenName) tokenObject += `  ${tokenName},\n`;
});
tokenObject += '};';
mainFileContent += tokenObject;

// Write out main file
writeFile('tokens', mainFileContent);
