/* eslint-disable no-undef */
import esbuild from 'esbuild';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));

esbuild
  .build({
    entryPoints: {
      index: join(__dirname, '../src/index.ts'),
    },
    bundle: true,
    format: 'esm',
    target: 'esnext',
    sourcemap: 'external',
    outdir: join(__dirname, '../dist/esm'),
  })
  .then(async () => {
    const kumoThemes = await import('../dist/esm/index.js');

    // Write individual tokens to file
    fs.writeFileSync(
      join(__dirname, '../dist/esm/tokens.js'),
      '// Auto generated by scripts/build.js\n' +
        Object.entries(kumoThemes.tokens)
          .map(([key, value]) => `export const ${key} = '${value}';\n`)
          .join(''),
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/tokens.d.ts'),
      '// Auto generated by scripts/build.js\n' +
        Object.keys(kumoThemes.tokens)
          .map((key) => `export declare const ${key}: string;\n`)
          .join(''),
    );

    // Write ressolved themes to file
    fs.writeFileSync(
      join(__dirname, '../dist/esm/lightTheme.js'),
      '// Auto generated by scripts/build.js\nexport const lightTheme = ' +
        JSON.stringify(kumoThemes.lightTheme(), null, 2),
    );
    fs.writeFileSync(
      join(__dirname, '../dist/esm/darkTheme.js'),
      '// Auto generated by scripts/build.js\nexport const darkTheme = ' +
        JSON.stringify(kumoThemes.darkTheme(), null, 2),
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/lightTheme.d.ts'),
      '// Auto generated by scripts/build.js\nimport type { Theme } from "./themes.d.ts";\nexport declare const lightTheme: Theme;\n',
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/darkTheme.d.ts'),
      '// Auto generated by scripts/build.js\nimport type { Theme } from "./themes.d.ts";\nexport declare const darkTheme: Theme;\n',
    );

    // Generate theme mapping
    const { lightTheme, darkTheme, GenerateAllPalettes } = kumoThemes;
    const seedColor = '#ff0000';
    const lightThemeColored = lightTheme(seedColor);
    const darkThemeColored = darkTheme(seedColor);
    const palettes = GenerateAllPalettes(seedColor);
    for (const themeKey of Object.keys(lightThemeColored)) {
      const lightValue = lightThemeColored[themeKey];
      const darkValue = darkThemeColored[themeKey];

      for (const palette of Object.keys(palettes)) {
        for (const variant of Object.keys(palettes[palette])) {
          const lightTone = Object.entries(palettes[palette][variant]).find(
            ([key, value]) => value === lightValue,
          );
          const darkTone = Object.entries(palettes[palette][variant]).find(
            ([key, value]) => value === darkValue,
          );
          if (lightTone) {
            lightThemeColored[themeKey] =
              `${palette}.${variant}.getTone(${lightTone[0]})`;
          }
          if (darkTone) {
            darkThemeColored[themeKey] =
              `${palette}.${variant}.getTone(${darkTone[0]})`;
          }
        }
      }
    }

    fs.writeFileSync(
      join(__dirname, '../dist/esm/lightThemeMapping.js'),
      '// Auto generated by scripts/build.js\n' +
        Object.entries(lightThemeColored)
          .map(([key, value]) => `export const ${key} = '${value}';\n`)
          .join(''),
    );
    fs.writeFileSync(
      join(__dirname, '../dist/esm/darkThemeMapping.js'),
      '// Auto generated by scripts/build.js\n' +
        Object.entries(darkThemeColored)
          .map(([key, value]) => `export const ${key} = '${value}';\n`)
          .join(''),
    );
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
