/* eslint-disable no-undef */
import esbuild from 'esbuild';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));

esbuild
  .build({
    entryPoints: {
      index: join(__dirname, '../src/index.ts'),
    },
    bundle: true,
    format: 'esm',
    target: 'esnext',
    sourcemap: 'external',
    outdir: join(__dirname, '../dist/esm'),
  })
  .then(async () => {
    const kumoThemes = await import('../dist/esm/index.js');

    // Write individual tokens to file
    fs.writeFileSync(
      join(__dirname, '../dist/esm/tokens.js'),
      '// Auto generated by scripts/build.js\n' +
        Object.entries(kumoThemes.tokens)
          .map(([key, value]) => `export const ${key} = '${value}';\n`)
          .join(''),
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/tokens.d.ts'),
      '// Auto generated by scripts/build.js\n' +
        Object.keys(kumoThemes.tokens)
          .map((key) => `export declare const ${key}: string;\n`)
          .join(''),
    );

    // Write ressolved themes to file
    fs.writeFileSync(
      join(__dirname, '../dist/esm/lightTheme.js'),
      '// Auto generated by scripts/build.js\nexport const lightTheme = ' +
        JSON.stringify(kumoThemes.lightTheme(), null, 2),
    );
    fs.writeFileSync(
      join(__dirname, '../dist/esm/darkTheme.js'),
      '// Auto generated by scripts/build.js\nexport const darkTheme = ' +
        JSON.stringify(kumoThemes.darkTheme(), null, 2),
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/lightTheme.d.ts'),
      '// Auto generated by scripts/build.js\nimport type { Theme } from "./themes.d.ts";\nexport declare const lightTheme: Theme;\n',
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/darkTheme.d.ts'),
      '// Auto generated by scripts/build.js\nimport type { Theme } from "./themes.d.ts";\nexport declare const darkTheme: Theme;\n',
    );
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
