/* eslint-disable no-undef */
import esbuild from 'esbuild';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));

esbuild
  .build({
    entryPoints: {
      index: join(__dirname, '../src/index.ts'),
    },
    bundle: true,
    format: 'esm',
    target: 'esnext',
    sourcemap: 'external',
    outdir: join(__dirname, '../dist/esm'),
  })
  .then(async () => {
    const kumoThemes = await import('../dist/esm/index.js');

    // Write individual tokens to file
    fs.writeFileSync(
      join(__dirname, '../dist/esm/tokens.js'),
      '// Auto generated by scripts/build.js\n' +
        Object.entries(kumoThemes.tokens)
          .map(([key, value]) => `export const ${key} = '${value}';\n`)
          .join(''),
    );
    fs.writeFileSync(
      join(__dirname, '../dist/dts/tokens.d.ts'),
      '// Auto generated by scripts/build.js\n' +
        Object.keys(kumoThemes.tokens)
          .map((key) => `export declare const ${key}: string;\n`)
          .join(''),
    );
  })
  .catch(() => process.exit(1));
