import { brandWeb } from './brandVariants.js';
import { type ColorTokens } from '@fluentui/tokens';

export declare interface WindowsColorTokens {
  colorBrandForeground1Hover: string;
  colorBrandForeground1Pressed: string;
  colorBrandForeground1Selected: string;
  colorBrandForeground2Selected: string;
  colorBrandStroke: string;
  colorBrandStrokeHover: string;
  colorBrandStrokePressed: string;
  colorLabelBerry: string;
  colorLabelBlue: string;
  colorLabelBrass: string;
  colorLabelHotPink: string;
  colorLabelMink: string;
  colorLabelPumpkin: string;
  colorLabelPurple: string;
  colorLabelRoyalBlue: string;
  colorLabelTeal: string;
  colorLayerBackgroundApp: string;
  colorLayerBackgroundBase: string;
  colorLayerBackgroundDialog: string;
  colorLayerBackgroundTooltip: string;
  colorLayerBackgroundTooltipStaticInverted: string;
  colorLayerStrokeBase: string;
  colorLayerStrokeFlyout: string;
  colorNeutralBackgroundTabActive: string;
  colorNeutralForegroundDisabledOnBrand: string;
  colorNeutralForegroundHint: string;
  colorNeutralForegroundOnLabel: string;
  colorNeutralBackgroundFloating: string;
  colorNeutralBackgroundFloatingHover: string;
  colorNeutralBackgroundFloatingPressed: string;
  colorNeutralBackgroundFloatingSelected: string;
  colorNeutralBackgroundFloatingDisabled: string;
  colorShellFillCaptionControlPrimaryHover: string;
  colorShellFillCaptionControlPrimaryPressed: string;
  colorShellForegroundCaptionControlPrimaryHover: string;
  colorShellForegroundCaptionControlPrimaryPressed: string;
  colorShellFillTaksbarItemPrimary: string;
  colorShellFillTaksbarItemSecondary: string;
  colorShellFillTaksbarItemTeritary: string;
  colorShellStrokeTaskbarItemQuinary: string;
  colorShellStrokeTaskbarItemSecondary: string;
  colorShellFillTaskbarItemIndicator: string;
  colorFillAccent: string;
}

export const lightThemeColorTokens: WindowsColorTokens = {
  colorBrandForeground1Hover: brandWeb[70],
  colorBrandForeground1Pressed: brandWeb[60],
  colorBrandForeground1Selected: brandWeb[80],
  colorBrandForeground2Selected: brandWeb[70],
  colorBrandStroke: brandWeb[80],
  colorBrandStrokeHover: brandWeb[70],
  colorBrandStrokePressed: brandWeb[60],
  colorLabelBerry: '#C239B3',
  colorLabelBlue: '#296EEB',
  colorLabelBrass: '#986F0B',
  colorLabelHotPink: '#E3008C',
  colorLabelMink: '#706D6B',
  colorLabelPumpkin: '#CA5010',
  colorLabelPurple: '#8230FF',
  colorLabelRoyalBlue: '#004E8C',
  colorLabelTeal: '#038387',
  colorLayerBackgroundApp: '#dde2e8',
  colorLayerBackgroundBase: '#FFFFFF80',
  colorLayerBackgroundDialog: '#FFFFFF',
  colorLayerBackgroundTooltip: '#FFFFFF',
  colorLayerBackgroundTooltipStaticInverted: '#333333',
  colorLayerStrokeBase: '#75757566',
  colorLayerStrokeFlyout: '#0000000F',
  colorNeutralBackgroundFloating: '#FFFFFF',
  colorNeutralBackgroundFloatingDisabled: '#F0F0F0',
  colorNeutralBackgroundFloatingHover: '#F5F5F5',
  colorNeutralBackgroundFloatingPressed: '#E0E0E0',
  colorNeutralBackgroundFloatingSelected: '#F0F0F0',
  colorNeutralBackgroundTabActive: '#FFFFFFD9',
  colorNeutralForegroundDisabledOnBrand: '#FFFFFF85',
  colorNeutralForegroundHint: '#0000008F',
  colorNeutralForegroundOnLabel: '#FFFFFF',
  colorShellFillTaksbarItemPrimary: '#FFFFFFB2',
  colorShellFillTaksbarItemSecondary: '#FFFFFF80',
  colorShellFillTaksbarItemTeritary: '#FFFFFF4D',
  colorShellStrokeTaskbarItemSecondary: '#0000000f',
  colorShellStrokeTaskbarItemQuinary: '#00000005',
  colorShellFillTaskbarItemIndicator: '#00000070',
  colorFillAccent: '#005FB8',
  colorShellFillCaptionControlPrimaryHover: '#C42B1C',
  colorShellFillCaptionControlPrimaryPressed: '#C42B1CE5',
  colorShellForegroundCaptionControlPrimaryHover: '#FFFFFF',
  colorShellForegroundCaptionControlPrimaryPressed: '#FFFFFFB2',
};

export const lightThemeSolidColorTokens: Partial<WindowsColorTokens> = {
  colorLayerBackgroundBase: '#FAFAFA',
};

export const lightThemeColorTokenOverrides: Partial<ColorTokens> = {
  colorBrandForeground2Pressed: brandWeb[40],
  colorNeutralBackground1: '#FFFFFFB3',
  colorNeutralBackground1Hover: '#0000000A',
  colorNeutralBackground1Pressed: '#0000001F',
  colorNeutralBackground1Selected: '#00000014',
  colorNeutralBackground2: '#00000005',
  colorNeutralBackground2Hover: '#0000000F',
  colorNeutralBackground2Pressed: '#00000024',
  colorNeutralBackground2Selected: '#00000019',
  colorNeutralBackground3: '#0000000A',
  colorNeutralBackground3Hover: '#00000014',
  colorNeutralBackground3Pressed: '#00000029',
  colorNeutralBackground3Selected: '#0000001F',
  colorNeutralBackground4: '#0000000F',
  colorNeutralBackground5: '#00000014',
  colorNeutralBackgroundDisabled: '#0000000F',
  colorNeutralForeground1: '#000000DB',
  colorNeutralForeground1Hover: '#000000DB',
  colorNeutralForeground1Pressed: '#000000DB',
  colorNeutralForeground1Selected: '#000000DB',
  colorNeutralForeground2: '#000000BD',
  colorNeutralForeground2Hover: '#000000DB',
  colorNeutralForeground2Pressed: '#000000DB',
  colorNeutralForeground2Selected: '#000000DB',
  colorNeutralForeground3: '#0000009e',
  colorNeutralForeground3Hover: '#0000009e',
  colorNeutralForeground3Pressed: '#0000009e',
  colorNeutralForeground3Selected: '#0000009e',
  colorNeutralForeground4: '#0000008F',
  colorNeutralForegroundDisabled: '#00000042',
  colorNeutralForegroundInvertedDisabled: '#FFFFFF66',
  colorNeutralForegroundStaticInverted: '#FFFFFF',
  colorNeutralStroke1: '#0000002E',
  colorNeutralStroke1Hover: '#00000038',
  colorNeutralStroke1Pressed: '#0000004C',
  colorNeutralStroke1Selected: '#00000042',
  colorNeutralStroke2: '#0000001F',
  colorNeutralStroke3: '#0000000F',
  colorNeutralStrokeAccessible: '#0000009E',
  colorNeutralStrokeAccessibleHover: '#000000A8',
  colorNeutralStrokeAccessiblePressed: '#000000B2',
  colorNeutralStrokeDisabled: '#0000001F',
  colorNeutralStrokeInvertedDisabled: '#FFFFFF66',
  colorNeutralStrokeOnBrand: '#FFFFFF',
  colorNeutralStrokeOnBrand2: '#FFFFFF',
  colorNeutralStrokeOnBrand2Hover: '#FFFFFF',
  colorNeutralStrokeOnBrand2Pressed: '#FFFFFF',
  colorNeutralStrokeOnBrand2Selected: '#FFFFFF',
  colorStrokeFocus1: '#FFFFFF',
  colorSubtleBackground: '#00000000',
  colorSubtleBackgroundHover: '#0000000A',
  colorSubtleBackgroundPressed: '#00000006',
  colorSubtleBackgroundSelected: '#00000014',
  colorNeutralCardBackground: '#FFFFFF',
  colorNeutralCardBackgroundHover: '#FAFAFA',
};

export const darkThemeColorTokens: WindowsColorTokens = {
  colorBrandForeground1Hover: brandWeb[120],
  colorBrandForeground1Pressed: brandWeb[130],
  colorBrandForeground1Selected: brandWeb[110],
  colorBrandForeground2Selected: brandWeb[120],
  colorBrandStroke: brandWeb[110],
  colorBrandStrokeHover: brandWeb[120],
  colorBrandStrokePressed: brandWeb[130],
  colorLabelBerry: '#CF87DA',
  colorLabelBlue: '#69A1FA',
  colorLabelBrass: '#C1A256',
  colorLabelHotPink: '#EE5FB7',
  colorLabelMink: '#84817E',
  colorLabelPumpkin: '#DF8E64',
  colorLabelPurple: '#B696FF',
  colorLabelRoyalBlue: '#4A89BA',
  colorLabelTeal: '#4CB4B7',
  colorLayerBackgroundApp: '#000',
  colorLayerBackgroundBase: '#3A3A3A4D',
  colorLayerBackgroundDialog: '#292929',
  colorLayerBackgroundTooltip: '#292929',
  colorLayerBackgroundTooltipStaticInverted: '#3D3D3D',
  colorLayerStrokeBase: '#75757566',
  colorLayerStrokeFlyout: '#00000033',
  colorNeutralBackgroundTabActive: '#FFFFFF22',
  colorNeutralForegroundDisabledOnBrand: '#FFFFFF3D',
  colorNeutralForegroundHint: '#FFFFFF85',
  colorNeutralForegroundOnLabel: '#000000e5',
  colorNeutralBackgroundFloating: '#292929',
  colorNeutralBackgroundFloatingHover: '#3D3D3D',
  colorNeutralBackgroundFloatingPressed: '#1F1F1F',
  colorNeutralBackgroundFloatingSelected: '#1F1F1F',
  colorNeutralBackgroundFloatingDisabled: '#141414',
  colorShellFillTaksbarItemPrimary: '#FFFFFF15',
  colorShellFillTaksbarItemSecondary: '#FFFFFF0F',
  colorShellFillTaksbarItemTeritary: '#FFFFFF0B',
  colorShellStrokeTaskbarItemSecondary: '#FFFFFF1A',
  colorShellStrokeTaskbarItemQuinary: '#FFFFFF0F',
  colorShellFillTaskbarItemIndicator: '#FFFFFF63',
  colorFillAccent: '#005FB8',
  colorShellFillCaptionControlPrimaryHover: '#C42B1C',
  colorShellFillCaptionControlPrimaryPressed: '#C42B1CE5',
  colorShellForegroundCaptionControlPrimaryHover: '#FFFFFF',
  colorShellForegroundCaptionControlPrimaryPressed: '#FFFFFFB2',
};

export const darkThemeSolidColorTokens: Partial<WindowsColorTokens> = {
  colorLayerBackgroundBase: '#1F1F1F',
};

export const darkThemeColorTokenOverrides: Partial<ColorTokens> = {
  colorBrandBackground2: brandWeb[40],
  colorBrandForeground1: brandWeb[110],
  colorBrandForeground2: brandWeb[120],
  colorBrandForeground2Pressed: brandWeb[110],
  colorBrandForegroundLink: brandWeb[110],
  colorBrandForegroundLinkHover: brandWeb[120],
  colorBrandForegroundLinkSelected: brandWeb[110],
  colorNeutralBackground1: '#FFFFFF0B',
  colorNeutralBackground1Hover: '#FFFFFF22',
  colorNeutralBackground1Pressed: '#FFFFFF00',
  colorNeutralBackground1Selected: '#FFFFFF1C',
  colorNeutralBackground2: '#3A3A3A4D',
  colorNeutralBackground2Hover: '#3A3A3ABF',
  colorNeutralBackground2Pressed: '#3A3A3A57',
  colorNeutralBackground2Selected: '#3A3A3AC9',
  colorNeutralBackground3: '#3A3A3A4D',
  colorNeutralBackground3Hover: '#3A3A3AB3',
  colorNeutralBackground3Pressed: '#3A3A3A2E',
  colorNeutralBackground3Selected: '#3A3A3A9E',
  colorNeutralBackground4: '#3A3A3A2E',
  colorNeutralBackgroundDisabled: '#3A3A3A4D',
  colorNeutralForeground1: '#FFFFFF',
  colorNeutralForeground1Hover: '#FFFFFF',
  colorNeutralForeground1Pressed: '#FFFFFF',
  colorNeutralForeground1Selected: '#FFFFFF',
  colorNeutralForeground2: '#FFFFFFD6',
  colorNeutralForeground2Hover: '#FFFFFF',
  colorNeutralForeground2Pressed: '#FFFFFF',
  colorNeutralForeground2Selected: '#FFFFFF',
  colorNeutralForeground3: '#FFFFFFAD',
  colorNeutralForeground3Hover: '#FFFFFFD6',
  colorNeutralForeground3Pressed: '#FFFFFFD6',
  colorNeutralForeground3Selected: '#FFFFFFD6',
  colorNeutralForeground4: '#FFFFFF85',
  colorNeutralForegroundDisabled: '#FFFFFF3D',
  colorNeutralForegroundInvertedDisabled: '#FFFFFF66',
  colorNeutralForegroundStaticInverted: '#FFFFFF',
  colorNeutralStroke1: '#FFFFFF49',
  colorNeutralStroke1Hover: '#FFFFFF75',
  colorNeutralStroke1Pressed: '#FFFFFF6B',
  colorNeutralStroke1Selected: '#FFFFFF70',
  colorNeutralStroke2: '#FFFFFF31',
  colorNeutralStroke3: '#FFFFFF3D',
  colorNeutralStrokeAccessible: '#FFFFFF',
  colorNeutralStrokeAccessibleHover: '#FFFFFF',
  colorNeutralStrokeAccessiblePressed: '#FFFFFF',
  colorNeutralStrokeDisabled: '#FFFFFF42',
  colorNeutralStrokeOnBrand2: '#FFFFFF',
  colorNeutralStrokeOnBrand2Hover: '#FFFFFF',
  colorNeutralStrokeOnBrand2Pressed: '#FFFFFF',
  colorNeutralStrokeOnBrand2Selected: '#FFFFFF',
  colorStrokeFocus2: '#FFFFFF',
  colorSubtleBackground: '#FFFFFF00',
  colorSubtleBackgroundHover: '#FFFFFF10',
  colorSubtleBackgroundPressed: '#FFFFFF0B',
  colorSubtleBackgroundSelected: '#FFFFFF22',
};
